import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {readMidi} from '../midi.mjs';
import {harmony,noteNames} from '../music.mjs';
const root=path.dirname(fileURLToPath(import.meta.url)),indexFile=await fs.access(path.join(root,'local/index.json')).then(()=> 'local/index.json',()=> 'index.json'),index=JSON.parse(await fs.readFile(path.join(root,indexFile),'utf8'));let analysed=0,failed=0;
for(const item of index.items){if(!item.local_path)continue;try{const raw=await fs.readFile(path.join(root,item.local_path)),midi=readMidi(raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.byteLength)),notes=midi.events.filter(e=>(e.data[0]&240)===144&&e.data[2]);const chroma=new Array(12).fill(0),bins=Array.from({length:64},()=>new Array(12).fill(0));let minimum=127,maximum=0,sum=0;
 for(const e of notes){chroma[e.data[1]%12]+=e.data[2];bins[Math.min(63,Math.floor(e.time/Math.max(1,midi.duration)*64))][e.data[1]%12]+=e.data[2];minimum=Math.min(minimum,e.data[2]);maximum=Math.max(maximum,e.data[2]);sum+=e.data[2];}
 const key=harmony(chroma),curve=bins.map(bin=>+harmony(bin,chroma).tension.toFixed(3)),meanTempo=midi.tempos.reduce((sum,t,i)=>sum+t.bpm*((midi.tempos[i+1]?.time??midi.duration)-t.time),0)/Math.max(1,midi.duration),density=notes.length/Math.max(1,midi.duration);
 item.fingerprint={method:'velocity-weighted note-on chroma; 64 time bins; MIDI-encoded tempo',key:noteNames[key.key]+' '+key.mode,mean_tempo:+meanTempo.toFixed(2),density:+density.toFixed(3),dynamic_range:maximum-minimum,mean_velocity:+(sum/Math.max(1,notes.length)).toFixed(2),tension_curve:curve,notes:notes.length};item.key=item.fingerprint.key;item.tempo=item.fingerprint.mean_tempo;item.duration=+midi.duration.toFixed(2);item.mood=density>8||item.fingerprint.mean_velocity>95?'intense':density<3?'calm':'flowing';item.tags=[item.era,item.mood,key.mode,maximum-minimum>55?'expressive':'even'];item.tag_basis={era:'composer/catalogue metadata; historical era cannot be inferred reliably from MIDI',mood:'note density and mean velocity',expression:'MIDI velocity range'};delete item.analysis_error;analysed++;
 }catch(e){item.analysis_error=e.message;failed++;}if((analysed+failed)%100===0)console.log({analysed,failed});}
await fs.writeFile(path.join(root,indexFile),JSON.stringify(index));const lookup=new Map(index.items.map(i=>[i.id,i]));for(const name of await fs.readdir(root)){if(!/^catalogue-.*\.json$/.test(name))continue;const old=JSON.parse(await fs.readFile(path.join(root,name),'utf8'));await fs.writeFile(path.join(root,name),JSON.stringify(old.map(i=>lookup.get(i.id)??i)));}console.log({analysed,failed,total:index.items.length});
