import {seeded,parameters,nextReform} from './av_patch.mjs';
import {particleField} from './particles.mjs';
import {features,microphoneAudio} from './audio.mjs';
import {works} from './works.mjs';
import {hash,initial} from './parser.mjs';
const $=id=>document.getElementById(id),scene=initial();
let seed=0,P,rng,field=particleField($('stage')),ctx,graph,epoch=0,nextEvent=0,nextMutation=0,eventIndex=0,lastReform=-Infinity,events=[],pulse=0,previous={},lastAnalysis=0,lastFrame=0,visualTime=0,paused=false,recording=false,activeVoices=0,stats={};
const mic=microphoneAudio(message=>$('status').textContent=message,()=>({enabled:!!ctx,rms:previous.rms??0}));
function evolution(){return {seed,symmetry:P.symmetry,breathRate:P.lfo[0],variant:P.variant,effect:P.effect,strength:P.strength,density:P.density,profile:works[P.work],clock:visualTime};}
function choose(value){if(recording){$('status').textContent='Finish recording before changing seed / 录制结束后切换种子';$('seed').value=String(seed);location.hash=String(seed);return;}previous={};pulse=0;seed=/^\d+$/.test(value)?Number(value)>>>0:hash(value);P=parameters(seed);rng=seeded(seed^0xa3c59ac3);location.hash=String(seed);$('seed').value=String(seed);events=[];eventIndex=0;lastReform=-Infinity;nextEvent=0;nextMutation=P.period;visualTime=0;if(ctx){epoch=ctx.currentTime+.1;graph?.stop();graph=makeGraph();}updateLabel();}
function updateLabel(){$('patch').textContent=`${works[P.work].name} · seed ${seed} · ${P.symmetry}-fold · ${P.wave} / ${P.filter}`;}
function vary(){P.variant+= (rng()-.5)*.6;P.strength=Math.max(.2,Math.min(1,P.strength+(rng()-.5)*.16));P.cutoff=Math.max(250,Math.min(3000,P.cutoff+(rng()-.5)*250));P.density=Math.max(.5,Math.min(1.5,P.density+(rng()-.5)*.12));graph?.filter.frequency.setTargetAtTime(P.cutoff,ctx.currentTime,.7);updateLabel();}
function makeGraph(){
 const nodes=[],bus=ctx.createGain(),filter=ctx.createBiquadFilter(),limiter=ctx.createDynamicsCompressor(),ceiling=ctx.createWaveShaper(),volume=ctx.createGain(),analyser=ctx.createAnalyser(),destination=ctx.createMediaStreamDestination();
 filter.type=P.filter;filter.frequency.value=P.cutoff;filter.Q.value=P.q;limiter.threshold.value=-18;limiter.knee.value=3;limiter.ratio.value=20;limiter.attack.value=.003;limiter.release.value=.15;
 // Hard output ceiling is independent of oscillator count and compressor attack.
 const curve=new Float32Array(4097);for(let i=0;i<curve.length;i++)curve[i]=.25*Math.tanh((i/(curve.length-1)*2-1)*4);ceiling.curve=curve;volume.gain.value=Number($('volume').value);
 bus.connect(filter);filter.connect(limiter);limiter.connect(ceiling);ceiling.connect(volume);volume.connect(analyser);analyser.connect(ctx.destination);analyser.connect(destination);analyser.fftSize=1024;
 const delay=ctx.createDelay(1),feedback=ctx.createGain();delay.delayTime.value=P.delay;feedback.gain.value=.2;filter.connect(delay);delay.connect(feedback);feedback.connect(delay);feedback.connect(limiter);
 const convolver=ctx.createConvolver(),wet=ctx.createGain(),ir=ctx.createBuffer(1,Math.floor(ctx.sampleRate*P.reverb),ctx.sampleRate),irData=ir.getChannelData(0),noiseRandom=seeded(seed^1297);for(let i=0;i<irData.length;i++)irData[i]=(noiseRandom()*2-1)*(1-i/irData.length)**3;convolver.buffer=ir;wet.gain.value=.15;filter.connect(convolver);convolver.connect(wet);wet.connect(limiter);
 const osc=ctx.createOscillator(),fm=ctx.createOscillator(),fmGain=ctx.createGain(),amp=ctx.createGain();osc.type=P.wave;osc.frequency.value=P.base;fm.frequency.value=P.base*P.ratio;fmGain.gain.value=P.base*.12;fm.connect(fmGain);fmGain.connect(osc.frequency);amp.gain.value=P.drone;osc.connect(amp);amp.connect(bus);osc.start(epoch);fm.start(epoch);nodes.push(osc,fm);
 P.lfo.forEach((rate,i)=>{const lfo=ctx.createOscillator(),depth=ctx.createGain();lfo.frequency.value=rate;depth.gain.value=i===0?P.cutoff*.25:i===1?P.drone*.3:P.base*.02;lfo.connect(depth);depth.connect(i===0?filter.frequency:i===1?amp.gain:osc.frequency);lfo.start(epoch);nodes.push(lfo);});
 const noise=ctx.createBuffer(1,ctx.sampleRate,ctx.sampleRate),data=noise.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=noiseRandom()*2-1;
 return {filter,volume,analyser,destination,noise,bus,samples:new Float32Array(analyser.fftSize),spectrum:new Float32Array(analyser.frequencyBinCount),stop(){nodes.forEach(n=>n.stop());bus.disconnect();filter.disconnect();delay.disconnect();feedback.disconnect();convolver.disconnect();wet.disconnect();analyser.disconnect();},gesture(at,kind,strength){if(activeVoices>=12)return;activeVoices++;const grain=ctx.createBufferSource(),g=ctx.createGain();grain.buffer=noise;grain.playbackRate.value=.5+strength;g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(.08+strength*.09,at+.008);g.gain.exponentialRampToValueAtTime(.0001,at+P.grain);grain.connect(g);g.connect(bus);grain.start(at,(eventIndex*.137)% .7);grain.stop(at+P.grain);grain.onended=()=>{activeVoices--;grain.disconnect();g.disconnect();};if(kind==='reform'){filter.frequency.setTargetAtTime(P.cutoff*1.8,at,.06);filter.frequency.setTargetAtTime(P.cutoff,at+.15,.4);}}};
}
async function toggle(){try{if(!ctx){ctx=new AudioContext();await ctx.resume();epoch=ctx.currentTime+.1;graph=makeGraph();visualTime=0;nextEvent=0;nextMutation=P.period;paused=false;}else{paused=!paused;await(paused?ctx.suspend():ctx.resume());}$('start').textContent=paused?'继续 / Resume':'暂停 / Pause';$('status').textContent=paused?'Paused':'Audio clock · 原创合成 / Original synthesis';}catch(e){$('status').textContent=e.message;}}
setInterval(()=>{if(!ctx||paused||ctx.state!=='running')return;const time=ctx.currentTime-epoch;if(nextEvent<time-.2)nextEvent=time;
 while(nextEvent<time+.1){const strength=rng(),kind='burst';if(strength<P.probability){const at=epoch+nextEvent;graph.gesture(at,kind,strength);events.push({time:nextEvent,strength,kind});}eventIndex++;nextEvent+=P.interval;}
 const reform=nextReform(P,time);if(reform<=time+.1&&reform>lastReform+.2){graph.gesture(epoch+reform,'reform',.7);events.push({time:reform,strength:.7,kind:'reform'});events.sort((a,b)=>a.time-b.time);lastReform=reform;}
 if($('auto').checked&&time>=nextMutation){vary();nextMutation+=P.period;}
},25);
function frame(ms){const dt=Math.min(.05,(ms-lastFrame)/1000||.016);lastFrame=ms;if(!paused){visualTime=ctx?Math.max(0,ctx.currentTime-epoch):visualTime+dt;pulse*=Math.exp(-dt*5);while(events.length&&events[0].time<=visualTime){const e=events.shift();pulse=1;if(e.kind==='reform')P.strength=Math.max(.2,P.strength*.96);}
 if(graph&&ms-lastAnalysis>33){graph.analyser.getFloatTimeDomainData(graph.samples);graph.analyser.getFloatFrequencyData(graph.spectrum);previous=features(graph.samples,graph.spectrum,ctx.sampleRate,previous);lastAnalysis=ms;}
 const m=mic.update(ms,dt),a={level:Math.min(1,(previous.level??0)*2+m.level*.4),warmth:previous.warmth??0,pitch:previous.pitch??0,pulse:Math.max(pulse,m.pulse??0)};
 if(field?.needsRebuild){field.canvas.remove();field=particleField($('stage'));}if(field)stats=field.draw(visualTime,dt,scene,a,false,evolution(),$('style').value)??{};
 if(Math.floor(ms/250)!==Math.floor((ms-dt*1000)/250))$('features').textContent=`${Math.round(1/dt)} fps · RMS ${(previous.rms??0).toFixed(3)} · ${Math.round(previous.centroid??0)} Hz · ${stats.particles??0} marks`;}
 requestAnimationFrame(frame);}
function save(){if(!field)return;const a=document.createElement('a');a.download=`voice-${seed}.png`;a.href=field.canvas.toDataURL();a.click();}
async function record(){if(recording)return;if(!ctx)await toggle();if(!ctx||!field)return;if(ctx.state!=='running')await toggle();if(!window.MediaRecorder||!field.canvas.captureStream){$('status').textContent='Recording unavailable in this browser';return;}const stream=field.canvas.captureStream(60);stream.addTrack(graph.destination.stream.getAudioTracks()[0].clone());const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(v=>MediaRecorder.isTypeSupported(v));if(!mime){$('status').textContent='WebM recording unavailable';stream.getTracks().forEach(t=>t.stop());return;}const rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:3000000}),chunks=[];recording=true;$('record').disabled=true;rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>{const url=URL.createObjectURL(new Blob(chunks,{type:mime})),a=document.createElement('a');a.href=url;a.download=`voice-${seed}.webm`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);stream.getTracks().forEach(t=>t.stop());recording=false;$('record').disabled=false;$('status').textContent='Recording saved / 已保存';};rec.start();$('status').textContent='Recording 15 seconds / 录制 15 秒';setTimeout(()=>rec.stop(),15000);}
$('start').onclick=toggle;$('random').onclick=()=>choose(String(crypto.getRandomValues(new Uint32Array(1))[0]));$('vary').onclick=vary;$('seed').onchange=()=>choose($('seed').value);$('volume').oninput=()=>graph?.volume.gain.setTargetAtTime(Number($('volume').value),ctx.currentTime,.1);$('save').onclick=save;$('record').onclick=record;$('mic').onclick=async()=>{if(mic.state.active)mic.stop();else await mic.start();$('mic').textContent=mic.state.active?'关闭麦克风 / Mic ON':'麦克风 / Mic OFF';};
function perform(){document.body.classList.toggle('performance');if(document.body.classList.contains('performance'))document.documentElement.requestFullscreen?.().catch(()=>{});else if(document.fullscreenElement)document.exitFullscreen?.();}
$('perform').onclick=perform;document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;const k=e.key.toLowerCase();if(k===' '){e.preventDefault();toggle();}if(k==='s')save();if(k==='r')record();if(k==='p')perform();});
addEventListener('hashchange',()=>{if(location.hash.slice(1)!==String(seed))choose(location.hash.slice(1)||'317');});
choose(location.hash.slice(1)||'317');if(!field)$('status').textContent='WebGL unavailable; try a GPU-enabled browser';requestAnimationFrame(frame);
window.avDebug={get seed(){return seed},get parameters(){return {...P}},get time(){return visualTime},get rms(){return previous.rms??0},get stats(){return stats},get audioState(){return ctx?.state??'off'}};
