import {renderer} from './renderer.mjs';
import {workbench} from './workbench.mjs';
import {midiPerformer} from './performer.mjs';
import {monetCanvas} from './monet.mjs';
import {cinematicGraph,cinematicParameters} from './cinematic.mjs';
import {seeded,parameters,nextReform} from './av_patch.mjs';
import {particleField} from './particles.mjs';
import {features,microphoneAudio} from './audio.mjs';
import {works} from './works.mjs';
import {hash,initial} from './parser.mjs';
const $=id=>document.getElementById(id),scene=initial();
let seed=0,P,rng,field=particleField($('stage')),ctx,graph,epoch=0,nextEvent=0,nextMutation=0,eventIndex=0,lastReform=-Infinity,events=[],pulse=0,previous={},lastAnalysis=0,lastFrame=0,visualTime=0,paused=false,recording=false,activeVoices=0,stats={};
const midi=midiPerformer(message=>$('status').textContent=message);
const isScore=()=>$('soundMode').value!=='electroacoustic';
const mic=microphoneAudio(message=>$('status').textContent=message,()=>({enabled:!!ctx,rms:previous.rms??0}));
const bench=workbench({clock:()=>visualTime,scene,seed:()=>seed,save,onInput:()=>{if($('soundMode').value!=='input'){$('soundMode').value='input';$('soundMode').dispatchEvent(new Event('change'));}},onMidi:data=>{midi.raw(data);if((data[0]&240)===144&&data[2]){pulse=1;graph?.note?.(data[1],data[2]);}}});
const light=document.createElement('canvas'),paint=document.createElement('canvas'),composite=document.createElement('canvas');$('stage').prepend(light,paint);let paintAudio={},paintEvolution={};const painter=renderer(paint,()=>scene,()=>({manual:true,style:$('style').value,evolution:paintEvolution,hasModel:bench.blender}),{update:()=>paintAudio});
function compose(){const source=['vangogh','ink'].includes($('style').value)?paint:$('style').value==='monet'?light:field?.canvas;if(!source)return composite;if(composite.width!==source.width)composite.width=source.width;if(composite.height!==source.height)composite.height=source.height;const c=composite.getContext('2d');c.clearRect(0,0,composite.width,composite.height);for(const v of document.querySelectorAll('video.blender.visible'))if(v.readyState>=2)c.drawImage(v,0,0,composite.width,composite.height);if($('style').value==='monet'||$('monetBlend').checked)c.drawImage(light,0,0,composite.width,composite.height);if($('style').value!=='monet')c.drawImage(source,0,0);return composite;}
function evolution(){return {seed,symmetry:P.symmetry,breathRate:graph?.breathRate??P.lfo[0],variant:P.variant,effect:P.effect,strength:P.strength,density:P.density,profile:works[P.work],clock:visualTime};}
function choose(value){if(recording){$('status').textContent='Finish recording before changing seed / 录制结束后切换种子';$('seed').value=String(seed);location.hash=String(seed);return;}bench.reset();previous={};pulse=0;seed=/^\d+$/.test(value)?Number(value)>>>0:hash(value);P=parameters(seed);rng=seeded(seed^0xa3c59ac3);location.hash=String(seed);$('seed').value=String(seed);events=[];eventIndex=0;lastReform=-Infinity;nextEvent=0;nextMutation=P.period;visualTime=0;if(ctx){epoch=ctx.currentTime+.1;midi.stop();graph?.stop();graph=makeGraph();}updateLabel();}
function updateLabel(){const score=cinematicParameters(seed);$('patch').textContent=`${works[P.work].name} · seed ${seed} · ${P.symmetry}-fold · ${isScore()?`${$('soundMode').selectedOptions[0].textContent} · ${Math.round(score.tempo)} BPM · ${score.scale[5]===9?'Dorian':'minor'}`:`${P.wave} / ${P.filter}`}`;}
function vary(){if($('work').value==='-1')P.work=Math.floor(rng()*works.length);graph?.requestVariation?.();P.variant+= (rng()-.5)*.6;P.strength=Math.max(.2,Math.min(1,P.strength+(rng()-.5)*.16));P.cutoff=Math.max(250,Math.min(3000,P.cutoff+(rng()-.5)*250));P.density=Math.max(.5,Math.min(1.5,P.density+(rng()-.5)*.12));graph?.filter.frequency.setTargetAtTime(P.cutoff,ctx.currentTime,.7);updateLabel();}
function makeGraph(){
 if(isScore())return cinematicGraph(ctx,{seed,performer:$('soundMode').value==='performer',external:$('soundMode').value==='input',pianoParts:Number($('pianoParts').value),pianoRandom:$('pianoRandom').checked,epoch,onEvent:e=>{midi.send(e,ctx,epoch);bench.event(e);if(e.kind==='pedal')return;events.push(e);events.sort((a,b)=>a.time-b.time)}});
 const nodes=[],bus=ctx.createGain(),filter=ctx.createBiquadFilter(),limiter=ctx.createDynamicsCompressor(),ceiling=ctx.createWaveShaper(),volume=ctx.createGain(),analyser=ctx.createAnalyser(),destination=ctx.createMediaStreamDestination();
 filter.type=P.filter;filter.frequency.value=P.cutoff;filter.Q.value=P.q;limiter.threshold.value=-18;limiter.knee.value=3;limiter.ratio.value=20;limiter.attack.value=.003;limiter.release.value=.15;
 // Hard output ceiling is independent of oscillator count and compressor attack.
 const curve=new Float32Array(4097);for(let i=0;i<curve.length;i++)curve[i]=.25*Math.tanh((i/(curve.length-1)*2-1)*4);ceiling.curve=curve;volume.gain.value=Number($('volume').value);
 bus.connect(filter);filter.connect(limiter);limiter.connect(ceiling);ceiling.connect(volume);volume.connect(analyser);analyser.connect(ctx.destination);analyser.connect(destination);analyser.fftSize=1024;
 const delay=ctx.createDelay(1),feedback=ctx.createGain();delay.delayTime.value=P.delay;feedback.gain.value=.2;filter.connect(delay);delay.connect(feedback);feedback.connect(delay);feedback.connect(limiter);
 const convolver=ctx.createConvolver(),wet=ctx.createGain(),ir=ctx.createBuffer(1,Math.floor(ctx.sampleRate*P.reverb),ctx.sampleRate),irData=ir.getChannelData(0),noiseRandom=seeded(seed^1297);for(let i=0;i<irData.length;i++)irData[i]=(noiseRandom()*2-1)*(1-i/irData.length)**3;convolver.buffer=ir;wet.gain.value=.15;filter.connect(convolver);convolver.connect(wet);wet.connect(limiter);
 const osc=ctx.createOscillator(),fm=ctx.createOscillator(),fmGain=ctx.createGain(),amp=ctx.createGain();osc.type=P.wave;osc.frequency.value=P.base;fm.frequency.value=P.base*P.ratio;fmGain.gain.value=P.base*.12;fm.connect(fmGain);fmGain.connect(osc.frequency);amp.gain.value=P.drone;osc.connect(amp);amp.connect(bus);osc.start(epoch);fm.start(epoch);nodes.push(osc,fm);
 P.lfo.forEach((rate,i)=>{const lfo=ctx.createOscillator(),depth=ctx.createGain();lfo.frequency.value=rate;depth.gain.value=i===0?P.cutoff*.25:i===1?P.drone*.3:P.base*.02;lfo.connect(depth);depth.connect(i===0?filter.frequency:i===1?amp.gain:osc.frequency);lfo.start(epoch);nodes.push(lfo);});
 const noise=ctx.createBuffer(1,ctx.sampleRate,ctx.sampleRate),data=noise.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=noiseRandom()*2-1;
 return {filter,volume,analyser,destination,noise,bus,samples:new Float32Array(analyser.fftSize),spectrum:new Float32Array(analyser.frequencyBinCount),stop(){nodes.forEach(n=>n.stop());bus.disconnect();filter.disconnect();delay.disconnect();feedback.disconnect();convolver.disconnect();wet.disconnect();analyser.disconnect();},gesture(at,kind,strength){if(activeVoices>=12)return;activeVoices++;const grain=ctx.createBufferSource(),g=ctx.createGain();grain.buffer=noise;grain.playbackRate.value=.5+strength;g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(.08+strength*.09,at+.008);g.gain.exponentialRampToValueAtTime(.0001,at+P.grain);grain.connect(g);g.connect(bus);grain.start(at,(eventIndex*.137)% .7);grain.stop(at+P.grain);grain.onended=()=>{activeVoices--;grain.disconnect();g.disconnect();};if(kind==='reform'){filter.frequency.setTargetAtTime(P.cutoff*1.8,at,.06);filter.frequency.setTargetAtTime(P.cutoff,at+.15,.4);}}};
}
async function toggle(){try{if(!ctx){ctx=new AudioContext();await ctx.resume();epoch=ctx.currentTime+.1;graph=makeGraph();visualTime=0;nextEvent=0;nextMutation=P.period;paused=false;}else{paused=!paused;if(paused)midi.stop();await(paused?ctx.suspend():ctx.resume());}$('start').textContent=paused?'继续 / Resume':'暂停 / Pause';$('status').textContent=paused?'Paused':'Audio clock · 原创合成 / Original synthesis';updateLabel();}catch(e){$('status').textContent=e.message;}}
setInterval(()=>{if(!ctx||paused||ctx.state!=='running')return;const time=ctx.currentTime-epoch;if(nextEvent<time-.2)nextEvent=time;
 if(graph.kind!=='cinematic'){while(nextEvent<time+.1){const strength=rng(),kind='burst';if(strength<P.probability){const at=epoch+nextEvent;graph.gesture(at,kind,strength);events.push({time:nextEvent,strength,kind});}eventIndex++;nextEvent+=P.interval;}
 const reform=nextReform(P,time);if(reform<=time+.1&&reform>lastReform+.2){graph.gesture(epoch+reform,'reform',.7);events.push({time:reform,strength:.7,kind:'reform'});events.sort((a,b)=>a.time-b.time);lastReform=reform;}}
 if($('auto').checked&&time>=nextMutation){vary();nextMutation+=P.period;}
},25);
function frame(ms){const dt=Math.min(.05,(ms-lastFrame)/1000||.016);lastFrame=ms;if(!paused){visualTime=ctx?Math.max(0,ctx.currentTime-epoch):visualTime+dt;pulse*=Math.exp(-dt*5);while(events.length&&events[0].time<=visualTime){const e=events.shift();pulse=1;if(e.kind==='reform')P.strength=Math.max(.2,P.strength*.96);}
 if(graph&&ms-lastAnalysis>33){graph.analyser.getFloatTimeDomainData(graph.samples);graph.analyser.getFloatFrequencyData(graph.spectrum);previous=features(graph.samples,graph.spectrum,ctx.sampleRate,previous);lastAnalysis=ms;}
 const m=mic.update(ms,dt);let a={level:Math.min(1,(previous.level??0)*2+m.level*.4),warmth:previous.warmth??0,pitch:previous.pitch??0,pulse:Math.max(pulse,m.pulse??0)};
 const mapped=bench.frame(visualTime,dt,evolution(),a);a=mapped.audio;
 if(field?.needsRebuild){field.canvas.remove();field=particleField($('stage'));}const style=$('style').value,painted=['vangogh','ink'].includes(style);paint.style.display=painted?'block':'none';if(painted){paintAudio=a;paintEvolution=mapped.evolution;painter.draw(ms);stats=painter.timing;}const lit=style==='monet'||style==='fusion'&&$('monetBlend').checked;light.style.display=lit?'block':'none';if(lit)stats=monetCanvas(light,visualTime,dt,scene,a,mapped.evolution,bench.blender);if(field){field.canvas.style.display=style==='monet'||painted?'none':'block';if(style!=='monet'&&!painted)stats=field.draw(visualTime,dt,scene,a,lit||bench.blender,mapped.evolution,style)??{};}graph?.update?.(visualTime,a,Number($('volume').value),P.variant,Number($('pianoParts').value),$('pianoRandom').checked);if(recording)compose();
 if(Math.floor(ms/250)!==Math.floor((ms-dt*1000)/250))$('features').textContent=`${Math.round(1/dt)} fps · RMS ${(previous.rms??0).toFixed(3)} · ${Math.round(previous.centroid??0)} Hz · ${stats.particles??stats.marks??0} marks${graph?.kind==='cinematic'?` · ${graph.params.performance?graph.params.performance.section+' · bar '+graph.params.performance.bar:graph.params.arrangement.name} · ${graph.params.arrangement.parts} parts`:''}`;}
 requestAnimationFrame(frame);}
function save(){if(!field&&$('style').value!=='monet')return;const a=document.createElement('a');a.download=`voice-${seed}.png`;a.href=compose().toDataURL();a.click();}
async function record(){if(recording)return;if(!ctx)await toggle();if(!ctx||!field&&$('style').value!=='monet')return;if(ctx.state!=='running')await toggle();if(!window.MediaRecorder||!composite.captureStream){$('status').textContent='Recording unavailable in this browser';return;}const stream=compose().captureStream(60);stream.addTrack(graph.destination.stream.getAudioTracks()[0].clone());const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(v=>MediaRecorder.isTypeSupported(v));if(!mime){$('status').textContent='WebM recording unavailable';stream.getTracks().forEach(t=>t.stop());return;}const rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:3000000}),chunks=[];recording=true;$('record').disabled=true;rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>{const url=URL.createObjectURL(new Blob(chunks,{type:mime})),a=document.createElement('a');a.href=url;a.download=`voice-${seed}.webm`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);stream.getTracks().forEach(t=>t.stop());recording=false;$('record').disabled=false;$('status').textContent='Recording saved / 已保存';};rec.start();$('status').textContent='Recording 15 seconds / 录制 15 秒';setTimeout(()=>rec.stop(),15000);}
$('soundMode').onchange=()=>{if(recording){$('soundMode').value=graph?.mode??'electroacoustic';return;}if(ctx){midi.stop();bench.reset();graph?.stop();events=[];graph=makeGraph();}$('pianoParts').hidden=!isScore();$('pianoRandomControl').hidden=$('soundMode').value!=='cinematic';updateLabel();};
$('midiConnect').onclick=async()=>{try{const outputs=await midi.discover();$('midiOutput').replaceChildren(new Option('MIDI OFF',''),...outputs.map(p=>new Option(p.name,p.id)));$('status').textContent=outputs.length?'选择输出设备 / Select an output':'未发现 MIDI 输出 / No MIDI outputs';}catch(e){$('status').textContent=e.message;}};$('midiOutput').onchange=()=>midi.select($('midiOutput').value);$('midiStop').onclick=()=>{midi.select('');$('midiOutput').value='';};addEventListener('pagehide',()=>midi.stop());
for(const [i,w] of works.entries())$('work').append(new Option(w.name,i));$('work').onchange=()=>{if(Number($('work').value)>=0)P.work=Number($('work').value);updateLabel();};
$('start').onclick=toggle;$('random').onclick=()=>choose(String(crypto.getRandomValues(new Uint32Array(1))[0]));$('vary').onclick=vary;$('seed').onchange=()=>choose($('seed').value);$('volume').oninput=()=>graph?.volume.gain.setTargetAtTime(Number($('volume').value),ctx.currentTime,.1);$('save').onclick=save;$('record').onclick=record;$('mic').onclick=async()=>{if(mic.state.active)mic.stop();else await mic.start();$('mic').textContent=mic.state.active?'关闭麦克风 / Mic ON':'麦克风 / Mic OFF';};
function perform(){document.body.classList.toggle('performance');if(document.body.classList.contains('performance'))document.documentElement.requestFullscreen?.().catch(()=>{});else if(document.fullscreenElement)document.exitFullscreen?.();}
$('perform').onclick=perform;document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;const k=e.key.toLowerCase();if(k===' '){e.preventDefault();toggle();}if(k==='s')save();if(k==='r')record();if(k==='p')perform();});
addEventListener('hashchange',()=>{if(location.hash.slice(1)!==String(seed))choose(location.hash.slice(1)||'317');});
choose(location.hash.slice(1)||'317');if(!field)$('status').textContent='WebGL unavailable; try a GPU-enabled browser';requestAnimationFrame(frame);
window.avDebug={get seed(){return seed},get parameters(){return {...P}},get time(){return visualTime},get rms(){return previous.rms??0},get stats(){return stats},get peak(){return graph?.samples.reduce((peak,v)=>Math.max(peak,Math.abs(v)),0)??0},get score(){return graph?.kind==='cinematic'?{...graph.params,time:graph.time,pulse:graph.pulse}:null},get audioState(){return ctx?.state??'off'}};
