import {seeded,nextReform} from './av_patch.mjs';
export function cinematicParameters(seed){const r=seeded(seed);return {root:[40,45,48,50][Math.floor(r()*4)],tempo:50+r()*20,scale:r()>.5?[0,2,3,5,7,8,10]:[0,2,3,5,7,9,10],progression:[[0,5,3,4],[0,3,6,0],[0,6,5,4]][Math.floor(r()*3)],phraseBeats:r()>.5?8:4,hall:3.5+r(),vibrato:4.4+r()*.7};}
function scoreChord(params,d){const scale=params.scale,note=i=>scale[i%7]+12*Math.floor(i/7);return d===4?[7,11,14]:[note(d),note(d+2),note(d+4)];}
export function cinematicArrangement(seed,phrase,maxParts=3,randomize=true){
 const r=seeded(seed^Math.imul(phrase+1,0x9e3779b1)),pattern=randomize?Math.floor(r()*4):0,inversion=randomize?Math.floor(r()*3):0;
 const parts=randomize&&phrase>0&&maxParts>1&&r()<.3?maxParts-1:maxParts,voices=parts===3?['bass','middle','treble']:parts===2?(randomize?[['bass','middle'],['bass','treble'],['middle','treble']][Math.floor(r()*3)]:['bass','middle']):[randomize&&r()<.35?'middle':'treble'];
 return {voices,name:randomize?['流动 / Flow','波浪 / Wave','回旋 / Turn','跳跃 / Leap'][pattern]:'固定 / Fixed',pattern,inversion,parts,rhythm:randomize?Math.floor(r()*3):0,bassOctave:randomize&&r()<.35?-12:0,trebleOctave:randomize&&r()<.2?12:0,spread:randomize?.22+r()*.23:.28,decay:randomize?2.5+r()*.9:3.2};
}
export function cinematicPianoNotes(params,degree,tick,parts=3,seed=317,arrangement=null){
 const a=arrangement??cinematicArrangement(seed,0,parts,false),base=scoreChord(params,degree),notes=[...base.slice(a.inversion),...base.slice(0,a.inversion).map(n=>n+12)],out=[],count=Math.min(parts,a.parts),active=a.voices.slice(0,count),expression=.88+.12*Math.sin(tick*1.91+seed);
 const add=(midi,strength,pan,part)=>out.push({midi:Math.max(21,Math.min(108,midi)),strength:strength*expression,pan,part,decay:a.decay});
 if(count===1){if(tick%4===0)add(params.root+(active[0]==='middle'?12:24+a.trebleOctave)+notes[(seed+tick/4)%3],.8,a.spread*.5,active[0]);return out;}
 if(active.includes('bass')&&tick%4===0)add(params.root+base[0]+a.bassOctave,.65,-a.spread,'bass');
 const patterns=[[0,1,2,1,0,2,1,2],[2,1,0,1,2,0,1,0],[0,2,0,1,0,2,1,2],[0,2,1,0,2,1,2,0]],index=patterns[a.pattern][(tick+seed%4)%8];
 if(active.includes('middle')&&(a.rhythm===0||a.rhythm===1&&tick%4!==3||a.rhythm===2&&tick%4!==2))add(params.root+12+notes[index],tick%2?.5:.65,-.08,'middle');
 if(active.includes('treble')&&tick%2===1&&(a.rhythm!==1||tick%4===3))add(params.root+24+base[(Math.floor(tick/2)+seed)%3]+a.trebleOctave,.7,a.spread,'treble');
 return out;
}
export function cinematicGraph(context,{seed=317,pianoParts=3,pianoRandom=true,epoch=context.currentTime+.1,destination=context.destination,onEvent=()=>{}}={}){
 let params=cinematicParameters(seed),beat=0,degree=0,chordIndex=0,lastCadence=-Infinity,lastPulse=-Infinity,closed=false,previousLevel=0,phraseChange=false;
 let arrangementIndex=-1,arrangement=cinematicArrangement(seed,0,pianoParts,pianoRandom);const noteCounts={bass:0,middle:0,treble:0,cadence:0};const state={pianoParts,pianoRandom,level:0,warmth:0,variant:seed%4096/650},bus=context.createGain(),filter=context.createBiquadFilter(),volume=context.createGain(),analyser=context.createAnalyser(),record=context.createMediaStreamDestination(),limiter=context.createDynamicsCompressor(),ceiling=context.createWaveShaper();bus.gain.value=2.5;filter.type='lowpass';filter.frequency.value=2000;bus.connect(filter);filter.connect(limiter);limiter.threshold.value=-18;limiter.ratio.value=12;limiter.attack.value=.004;limiter.release.value=.3;const curve=new Float32Array(4097);for(let i=0;i<curve.length;i++)curve[i]=.25*Math.tanh((i/(curve.length-1)*2-1)*4);ceiling.curve=curve;limiter.connect(ceiling);ceiling.connect(volume);volume.gain.value=.32;volume.connect(analyser);analyser.connect(destination);analyser.connect(record);analyser.fftSize=2048;
 const random=seeded(seed^8143),hall=context.createConvolver(),wet=context.createGain(),ir=context.createBuffer(2,Math.floor(context.sampleRate*params.hall),context.sampleRate);for(let ch=0;ch<2;ch++){const data=ir.getChannelData(ch);for(let i=0;i<data.length;i++)data[i]=(random()*2-1)*(1-i/data.length)**2.7;}hall.buffer=ir;wet.gain.value=.38;filter.connect(hall);hall.connect(wet);wet.connect(limiter);
 const bowFilter=context.createBiquadFilter();bowFilter.type='lowpass';bowFilter.frequency.value=750;bowFilter.Q.value=.6;bowFilter.connect(bus);const nodes=[],plucks=new Set();
 const bowed=[0,7].map((offset,i)=>{const oscillator=context.createOscillator(),gain=context.createGain(),vibrato=context.createOscillator(),depth=context.createGain();oscillator.type=i?'sawtooth':'square';oscillator.frequency.value=440*2**((params.root+offset-69)/12);gain.gain.value=.025;vibrato.frequency.value=params.vibrato;depth.gain.value=3.5;vibrato.connect(depth);depth.connect(oscillator.detune);oscillator.connect(gain);gain.connect(bowFilter);oscillator.start(epoch);vibrato.start(epoch);nodes.push(oscillator,vibrato);return {oscillator,gain};});
 const noise=context.createBufferSource(),bowNoise=context.createBiquadFilter(),noiseGain=context.createGain(),buffer=context.createBuffer(1,context.sampleRate*2,context.sampleRate),samples=buffer.getChannelData(0);for(let i=0;i<samples.length;i++)samples[i]=(random()*2-1)*Math.min(1,i/200,(samples.length-i)/200);noise.buffer=buffer;noise.loop=true;bowNoise.type='bandpass';bowNoise.frequency.value=1200;bowNoise.Q.value=.6;noiseGain.gain.value=.004;noise.connect(bowNoise);bowNoise.connect(noiseGain);noiseGain.connect(bus);noise.start(epoch);nodes.push(noise);
 const chord=d=>scoreChord(params,d);
 function changeChord(at,d){degree=d;const notes=chord(d);bowed.forEach(({oscillator,gain},i)=>{oscillator.frequency.setTargetAtTime(440*2**((params.root+notes[i?2:0]-69)/12),at,.45);gain.gain.setTargetAtTime(.02+state.level*.035,at,.5);});}
 function pluck(at,midi,strength=.4,pan=0,part='cadence',decay=3.2){if(plucks.size>=24)return;noteCounts[part]++;const group=[],stereo=context.createStereoPanner();stereo.pan.value=pan;stereo.connect(bus);for(const [i,ratio] of [1,2.006,3.019].entries()){const o=context.createOscillator(),g=context.createGain();o.frequency.value=440*2**((midi-69)/12)*ratio;o.type='sine';g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime((i===0?.16:i===1?.045:.02)*strength,at+.008);g.gain.exponentialRampToValueAtTime(.0001,at+decay-i*.4);o.connect(g);g.connect(stereo);o.start(at);o.stop(at+decay+.1);group.push(o);o.onended=()=>{o.disconnect();g.disconnect();if(i===0){plucks.delete(group);stereo.disconnect()}};}plucks.add(group);lastPulse=at-epoch;onEvent({time:at-epoch,strength,kind:'piano',part,midi});}
 function gesture(at,kind,strength=.5){if(kind!=='reform'||Math.abs(at-lastCadence)<.25)return;lastCadence=at;changeChord(at,0);pluck(at,params.root+24,Math.max(.3,strength));if(state.pianoParts>1){pluck(at+.035,params.root,.28,-.25);pluck(at+.07,params.root+19,.24,.1);}onEvent({time:at-epoch,strength,kind:'reform'});}
 const timer=setInterval(()=>{if(closed||context.state!=='running')return;const time=context.currentTime-epoch,seconds=30/params.tempo;if(beat*seconds<time-.2)beat=Math.ceil(time/seconds);
  while(beat*seconds<time+.1){const at=epoch+beat*seconds;if(beat%(params.phraseBeats*2)===0||phraseChange){changeChord(at,params.progression[chordIndex++%params.progression.length]);arrangement=cinematicArrangement(seed,++arrangementIndex,state.pianoParts,state.pianoRandom);phraseChange=false;}for(const note of cinematicPianoNotes(params,degree,beat,state.pianoParts,seed,arrangement))pluck(at,note.midi,note.strength*(.35+state.level*.4),note.pan,note.part,note.decay);beat++;}
  const reform=nextReform(state,Math.max(0,time));if(reform<=time+.1&&epoch+reform>lastCadence+.25)gesture(epoch+reform,'reform',.5);
 },25);
 return {kind:'cinematic',epoch,filter,volume,analyser,destination:record,samples:new Float32Array(2048),spectrum:new Float32Array(1024),gesture,
 get time(){return Math.max(0,context.currentTime-epoch)},get breathRate(){return params.tempo/(60*params.phraseBeats)},get pulse(){const age=context.currentTime-epoch-lastPulse;return age>=0?Math.exp(-age*5):0},get params(){return {...params,pianoParts:state.pianoParts,pianoRandom:state.pianoRandom,arrangement:{...arrangement},phrase:arrangementIndex,noteCounts:{...noteCounts},activeNotes:plucks.size}},
 setSeed(next){if(next===seed)return;seed=next;params=cinematicParameters(seed);beat=Math.ceil((context.currentTime-epoch)/(30/params.tempo));chordIndex=0;arrangementIndex=-1;phraseChange=true;},
 update(time,a,gain=.32,variant=state.variant,parts=3,randomize=true){const oldParts=state.pianoParts,oldRandom=state.pianoRandom;state.pianoRandom=!!randomize;state.pianoParts=Math.max(1,Math.min(3,Math.round(parts)||3));if(oldParts!==state.pianoParts||oldRandom!==state.pianoRandom)arrangement=cinematicArrangement(seed,Math.max(0,arrangementIndex),state.pianoParts,state.pianoRandom);const at=context.currentTime;state.variant=variant;state.level=Math.min(1,a.level??0);state.warmth=a.warmth??0;if(previousLevel>.45&&state.level<previousLevel-.1)phraseChange=true;previousLevel=previousLevel*.97+state.level*.03;bowFilter.frequency.setTargetAtTime(550+state.warmth*900+state.level*500,at,.4);noiseGain.gain.setTargetAtTime(.003+state.level*.006,at,.3);bowed.forEach(({gain:g},i)=>g.gain.setTargetAtTime((.022+state.level*.03)*(.75+.25*Math.sin(time*params.tempo/(60*params.phraseBeats)*Math.PI*2+i*.2)),at,.12));volume.gain.setTargetAtTime(gain*(.65+state.level*.35),at,.15);},
 stop(){if(closed)return;closed=true;clearInterval(timer);nodes.forEach(n=>n.stop());for(const group of plucks)group.forEach(o=>o.stop());bus.disconnect();filter.disconnect();wet.disconnect();analyser.disconnect();},close(){this.stop()}};
}
