import {seeded,nextReform} from './av_patch.mjs';
export function cinematicParameters(seed){const r=seeded(seed);return {root:[40,45,48,50][Math.floor(r()*4)],tempo:50+r()*20,scale:r()>.5?[0,2,3,5,7,8,10]:[0,2,3,5,7,9,10],progression:[[0,5,3,4],[0,3,6,0],[0,6,5,4]][Math.floor(r()*3)],phraseBeats:r()>.5?8:4,hall:3.5+r(),vibrato:4.4+r()*.7};}
export function cinematicGraph(context,{seed=317,epoch=context.currentTime+.1,destination=context.destination,onEvent=()=>{}}={}){
 let params=cinematicParameters(seed),beat=0,degree=0,chordIndex=0,lastCadence=-Infinity,lastPulse=-Infinity,closed=false,previousLevel=0,phraseChange=false;
 const state={level:0,warmth:0,variant:seed%4096/650},bus=context.createGain(),filter=context.createBiquadFilter(),volume=context.createGain(),analyser=context.createAnalyser(),record=context.createMediaStreamDestination(),limiter=context.createDynamicsCompressor(),ceiling=context.createWaveShaper();filter.type='lowpass';filter.frequency.value=2000;bus.connect(filter);filter.connect(limiter);limiter.threshold.value=-18;limiter.ratio.value=12;limiter.attack.value=.004;limiter.release.value=.3;const curve=new Float32Array(4097);for(let i=0;i<curve.length;i++)curve[i]=.25*Math.tanh((i/(curve.length-1)*2-1)*4);ceiling.curve=curve;limiter.connect(ceiling);ceiling.connect(volume);volume.gain.value=.32;volume.connect(analyser);analyser.connect(destination);analyser.connect(record);analyser.fftSize=2048;
 const random=seeded(seed^8143),hall=context.createConvolver(),wet=context.createGain(),ir=context.createBuffer(2,Math.floor(context.sampleRate*params.hall),context.sampleRate);for(let ch=0;ch<2;ch++){const data=ir.getChannelData(ch);for(let i=0;i<data.length;i++)data[i]=(random()*2-1)*(1-i/data.length)**2.7;}hall.buffer=ir;wet.gain.value=.38;filter.connect(hall);hall.connect(wet);wet.connect(limiter);
 const bowFilter=context.createBiquadFilter();bowFilter.type='lowpass';bowFilter.frequency.value=750;bowFilter.Q.value=.6;bowFilter.connect(bus);const nodes=[],plucks=new Set();
 const bowed=[0,7].map((offset,i)=>{const oscillator=context.createOscillator(),gain=context.createGain(),vibrato=context.createOscillator(),depth=context.createGain();oscillator.type=i?'sawtooth':'square';oscillator.frequency.value=440*2**((params.root+offset-69)/12);gain.gain.value=.025;vibrato.frequency.value=params.vibrato;depth.gain.value=3.5;vibrato.connect(depth);depth.connect(oscillator.detune);oscillator.connect(gain);gain.connect(bowFilter);oscillator.start(epoch);vibrato.start(epoch);nodes.push(oscillator,vibrato);return {oscillator,gain};});
 const noise=context.createBufferSource(),bowNoise=context.createBiquadFilter(),noiseGain=context.createGain(),buffer=context.createBuffer(1,context.sampleRate*2,context.sampleRate),samples=buffer.getChannelData(0);for(let i=0;i<samples.length;i++)samples[i]=(random()*2-1)*Math.min(1,i/200,(samples.length-i)/200);noise.buffer=buffer;noise.loop=true;bowNoise.type='bandpass';bowNoise.frequency.value=1200;bowNoise.Q.value=.6;noiseGain.gain.value=.004;noise.connect(bowNoise);bowNoise.connect(noiseGain);noiseGain.connect(bus);noise.start(epoch);nodes.push(noise);
 function chord(d){const scale=params.scale;const note=i=>scale[i%7]+12*Math.floor(i/7);return d===4?[7,11,14]:[note(d),note(d+2),note(d+4)];}
 function changeChord(at,d){degree=d;const notes=chord(d);bowed.forEach(({oscillator,gain},i)=>{oscillator.frequency.setTargetAtTime(440*2**((params.root+notes[i?2:0]-69)/12),at,.45);gain.gain.setTargetAtTime(.02+state.level*.035,at,.5);});}
 function pluck(at,midi,strength=.4){if(plucks.size>=12)return;const group=[];for(const [i,ratio] of [1,2.006,3.019].entries()){const o=context.createOscillator(),g=context.createGain();o.frequency.value=440*2**((midi-69)/12)*ratio;o.type='sine';g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime((i===0?.16:i===1?.045:.02)*strength,at+.008);g.gain.exponentialRampToValueAtTime(.0001,at+3.2-i*.4);o.connect(g);g.connect(bus);o.start(at);o.stop(at+3.3);group.push(o);o.onended=()=>{o.disconnect();g.disconnect();if(i===0)plucks.delete(group)};}plucks.add(group);lastPulse=at-epoch;onEvent({time:at-epoch,strength,kind:'piano'});}
 function gesture(at,kind,strength=.5){if(kind!=='reform'||Math.abs(at-lastCadence)<.25)return;lastCadence=at;changeChord(at,0);pluck(at,params.root+24,Math.max(.3,strength));onEvent({time:at-epoch,strength,kind:'reform'});}
 const timer=setInterval(()=>{if(closed||context.state!=='running')return;const time=context.currentTime-epoch,seconds=60/params.tempo;if(beat*seconds<time-.2)beat=Math.ceil(time/seconds);
  while(beat*seconds<time+.1){const at=epoch+beat*seconds;if(beat%params.phraseBeats===0||phraseChange){changeChord(at,params.progression[chordIndex++%params.progression.length]);phraseChange=false;}if(beat%2===0){const notes=chord(degree),index=(seed+Math.floor(beat/2))%3;pluck(at,params.root+24+notes[index],.25+state.level*.45);}beat++;}
  const reform=nextReform(state,Math.max(0,time));if(reform<=time+.1&&epoch+reform>lastCadence+.25)gesture(epoch+reform,'reform',.5);
 },25);
 return {kind:'cinematic',epoch,filter,volume,analyser,destination:record,samples:new Float32Array(2048),spectrum:new Float32Array(1024),gesture,
 get time(){return Math.max(0,context.currentTime-epoch)},get breathRate(){return params.tempo/(60*params.phraseBeats)},get pulse(){const age=context.currentTime-epoch-lastPulse;return age>=0?Math.exp(-age*5):0},get params(){return params},
 setSeed(next){if(next===seed)return;seed=next;params=cinematicParameters(seed);beat=Math.ceil((context.currentTime-epoch)/(60/params.tempo));chordIndex=0;phraseChange=true;},
 update(time,a,gain=.32,variant=state.variant){const at=context.currentTime;state.variant=variant;state.level=Math.min(1,a.level??0);state.warmth=a.warmth??0;if(previousLevel>.45&&state.level<previousLevel-.1)phraseChange=true;previousLevel=previousLevel*.97+state.level*.03;bowFilter.frequency.setTargetAtTime(550+state.warmth*900+state.level*500,at,.4);noiseGain.gain.setTargetAtTime(.003+state.level*.006,at,.3);bowed.forEach(({gain:g},i)=>g.gain.setTargetAtTime((.022+state.level*.03)*(.75+.25*Math.sin(time*params.tempo/(60*params.phraseBeats)*Math.PI*2+i*.2)),at,.12));volume.gain.setTargetAtTime(gain*(.65+state.level*.35),at,.15);},
 stop(){if(closed)return;closed=true;clearInterval(timer);nodes.forEach(n=>n.stop());for(const group of plucks)group.forEach(o=>o.stop());bus.disconnect();filter.disconnect();wet.disconnect();analyser.disconnect();},close(){this.stop()}};
}
