import {connectomeData} from './connectome_data.mjs';
export function connectomeLayer(stage){
 const canvas=document.createElement('canvas');canvas.hidden=true;canvas.style.zIndex=4;canvas.style.pointerEvents='none';stage.append(canvas);const gl=canvas.getContext('webgl2',{alpha:true,premultipliedAlpha:false,preserveDrawingBuffer:true});if(!gl)return {canvas,draw(){},available:false};
 const nodes=connectomeData.nodes,edges=[...connectomeData.edges].sort((a,b)=>Number(nodes[b[1]].instance.includes('GF'))-Number(nodes[a[1]].instance.includes('GF'))||b[2]-a[2]);let count=2000,average=16.7;
 function program(vertex,fragment){const p=gl.createProgram();for(const [type,source] of [[gl.VERTEX_SHADER,vertex],[gl.FRAGMENT_SHADER,fragment]]){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));gl.attachShader(p,s);gl.deleteShader(s);}gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p;}
 const projection=`vec3 orbit(vec3 p){float a=time*.08;return vec3(cos(a)*p.x+sin(a)*p.z,p.y,-sin(a)*p.x+cos(a)*p.z);}vec4 project(vec3 p){p=orbit(p);float z=2.8-p.z*.4;return vec4(p.x*1.8/z/aspect,p.y*1.6/z,0,1);}`;
 const edge=program(`#version 300 es
 precision highp float;in vec3 source;in vec3 target;in vec2 info;uniform float time,aspect,level,pulse,pedal;out float alpha;${projection}
 void main(){int segment=gl_VertexID/6;int v=gl_VertexID%6;float t=(float(segment)+float(v==1||v==2||v==4))/12.;float side=(v==0||v==1||v==3)?-1.:1.;vec3 bend=(source+target)*.5+vec3(0,.12,.25*sin(float(gl_InstanceID)*1.7));vec3 p=mix(mix(source,bend,t),mix(bend,target,t),t);vec3 q=mix(mix(source,bend,min(1.,t+.01)),mix(bend,target,min(1.,t+.01)),min(1.,t+.01));vec4 screen=project(p);vec2 tangent=normalize(project(q).xy-screen.xy+vec2(.00001));screen.xy+=vec2(-tangent.y,tangent.x)*side*(.0006+info.x*.0005+level*.0005);gl_Position=screen;float travel=fract(time*(.18+level*.9)+float(gl_InstanceID)*.017);float signal=exp(-pow((t-travel)/(.025+pedal*.09),2.));alpha=(.045+info.x*.07)+(signal*(.12+level*.5+pulse*info.y))*(.4+info.x*.2);}`,
 `#version 300 es
 precision highp float;in float alpha;uniform vec3 colour;out vec4 outColour;void main(){outColour=vec4(colour*alpha,alpha);}`);
 const node=program(`#version 300 es
 precision highp float;in vec3 position;in float gf;uniform float time,aspect,level,pulse,pedal;out float light;${projection}
 void main(){gl_Position=project(position);gl_PointSize=3.+gf*5.+level*3.+pulse*gf*7.;light=.4+level*.5+pulse*gf;}`,
 `#version 300 es
 precision highp float;in float light;uniform vec3 colour;out vec4 outColour;void main(){float a=exp(-dot(gl_PointCoord-.5,gl_PointCoord-.5)*16.)*light;outColour=vec4(colour*a,a);}`);
 const edgeArray=new Float32Array(edges.flatMap(([a,b,w])=>[...nodes[a].position,...nodes[b].position,Math.log1p(w)/4,nodes[b].instance.includes('GF')?1:0])),nodeArray=new Float32Array(nodes.flatMap(n=>[...n.position,n.instance.includes('GF')?1:0]));
 function buffer(data){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);return b;}const eb=buffer(edgeArray),nb=buffer(nodeArray);
 function attribute(p,name,size,stride,offset,divisor){const loc=gl.getAttribLocation(p,name);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,gl.FLOAT,false,stride,offset);gl.vertexAttribDivisor(loc,divisor);}
 function uniforms(p,time,a,e,style){gl.useProgram(p);const f=e.piano??{};for(const [name,value] of Object.entries({time,aspect:canvas.width/canvas.height,level:a.level,pulse:a.pulse,pedal:f.pedal??0}))gl.uniform1f(gl.getUniformLocation(p,name),value);const colour=style==='monet'?[.24,.38,.7]:style==='fusion'?(f.colour??[.8,.65,.25]):[.08,.6,1];gl.uniform3fv(gl.getUniformLocation(p,'colour'),colour);}
 return {canvas,available:true,data:connectomeData,draw(time,dt,a,e,style){if(canvas.hidden)return;const width=Math.min(1920,Math.round(stage.clientWidth*devicePixelRatio)),height=Math.round(width*stage.clientHeight/stage.clientWidth);if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}average=average*.97+dt*1000*.03;if(average>20)count=Math.max(400,count-8);else if(average<17)count=Math.min(4000,count+2);const wanted=Math.min(edges.length,Math.floor(count*(.35+(e.piano?.tension??0)*.65)));gl.viewport(0,0,width,height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.enable(gl.BLEND);gl.blendFunc(gl.ONE,gl.ONE);uniforms(edge,time,a,e,style);gl.bindBuffer(gl.ARRAY_BUFFER,eb);attribute(edge,'source',3,32,0,1);attribute(edge,'target',3,32,12,1);attribute(edge,'info',2,32,24,1);gl.drawArraysInstanced(gl.TRIANGLES,0,72,wanted);uniforms(node,time,a,e,style);gl.bindBuffer(gl.ARRAY_BUFFER,nb);attribute(node,'position',3,16,0,0);attribute(node,'gf',1,16,12,0);gl.drawArrays(gl.POINTS,0,nodes.length);return {nodes:nodes.length,edges:wanted,totalEdges:edges.length,layout:connectomeData.layout};}};
}
