// One model request returns music and visuals together. Local clock executes the data.
export function director({begin,apply,stop,output,device,status}){
 const form=document.getElementById('directorForm'),input=document.getElementById('directorText');let controller,timer,revision=0,previous=null,requestText='';
 const cancel=()=>{revision++;clearTimeout(timer);controller?.abort();};
 async function compose(version){controller=new AbortController();const deadline=setTimeout(()=>controller.abort(),65000);status(previous?'演出继续，正在构思下一乐句…':'正在同时谱写音乐与画面…');try{const response=await fetch('./api/performance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:requestText,previous}),signal:controller.signal});if(!response.ok)throw Error('需要本地 GPT-6 服务；静态网页无法调用模型');const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',accepted=false;while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value??new Uint8Array(),{stream:!done});let newline;while((newline=buffer.indexOf('\n'))>=0){const event=JSON.parse(buffer.slice(0,newline));buffer=buffer.slice(newline+1);if(event.plan&&version===revision){previous=event.plan;apply(event.plan);accepted=true;status(event.plan.description+' · GPT-6 '+(event.latency_ms/1000).toFixed(1)+'s');}}if(done)break;}if(!accepted)throw Error('模型未返回有效演出计划');if(version===revision)timer=setTimeout(()=>compose(version),Math.max(8000,previous.beats*60/previous.tempo*300));}catch(e){if(version===revision)status((previous?'保持上一段演出。':'')+(e.name==='AbortError'?'模型超时，请稍后再试。':e.message));}finally{clearTimeout(deadline);}}
 form.onsubmit=async e=>{e.preventDefault();const text=input.value.trim();if(!text)return;input.value='';cancel();if(/^(停止|停|stop|暂停)$/i.test(text)){await stop();previous=null;status('已停止。描述下一场演出即可开始。');return;}if(/^(全屏|fullscreen)$/i.test(text)){document.documentElement.requestFullscreen?.().catch(()=>{});return;}try{if(/MIDI|数码钢琴|外接乐器/i.test(text)){await output('midi');const name=text.match(/(?:设备|device)[:：\s]+([^，。,]+)/i)?.[1]??'';await device(name);}else if(/浏览器|browser/i.test(text))await output('browser');requestText=text;await begin();compose(revision);}catch(e){status(e.message);}};
 fetch('./api/status').then(r=>{if(!r.ok)throw Error();status('说出一场演出。输入“停止”结束。');}).catch(()=>status('模型演出需要本地服务：python3 run.py。此页面不会模拟模型回复。'));
 addEventListener('pagehide',cancel);
}
