// Original procedural impressionist light: no images, textures or external assets.
const states=new WeakMap(),TAU=Math.PI*2;const rand=n=>{const v=Math.sin(n*127.1+311.7)*43758.5453;return v-Math.floor(v)};
export function monetCanvas(canvas,time,dt,scene,a,evolution={},hasModel=false){
 let state=states.get(canvas);if(!state){state={count:1700,average:16.7,last:0,pulse:0,ripples:[],seed:0};states.set(canvas,state);}const seed=evolution.seed??317;if(seed!==state.seed){state.ripples=[];state.seed=seed;}
 state.average=state.average*.96+Math.min(100,dt*1000)*.04;if(evolution.deterministic)state.count=1700;else if(time-state.last>1){if(state.average>20)state.count=Math.max(650,Math.floor(state.count*.85));else if(state.average<17.5)state.count=Math.min(1900,state.count+60);state.last=time;}
 const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio,2),c=canvas.getContext('2d');if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}c.setTransform(dpr,0,0,dpr,0,0);c.globalCompositeOperation='source-over';c.clearRect(0,0,w,h);c.globalAlpha=hasModel?.25:1;
 const sky=c.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#aac5de');sky.addColorStop(.52,'#e9e3d3');sky.addColorStop(1,'#95b4c6');c.fillStyle=sky;c.fillRect(0,0,w,h);c.fillStyle='#ffe9bf';c.globalAlpha=.08+a.warmth*.2;c.fillRect(0,0,w,h);c.globalAlpha=1;
 const sx=w*(.65+Math.sin(seed)*.08),sy=h*.18,glow=c.createRadialGradient(sx,sy,0,sx,sy,w*.48);glow.addColorStop(0,`rgba(255,249,213,${.6+a.level*.35})`);glow.addColorStop(.3,'rgba(255,244,219,.35)');glow.addColorStop(1,'rgba(255,250,230,0)');c.fillStyle=glow;c.fillRect(0,0,w,h);
 for(let ray=0;ray<4;ray++){c.fillStyle='rgba(255,245,209,.055)';c.beginPath();c.moveTo(sx+(ray-2)*14,sy);c.lineTo(sx+(ray-2.2)*w*.21,h);c.lineTo(sx+(ray-1.8)*w*.21,h);c.fill();}
 c.lineCap='round';const colours=['#e7e8e8','#f9f0d7','#c7c7dd','#adc8db','#edddb6','#fff8e4'];
 function dab(x,y,length,angle,width,colour,alpha){c.globalAlpha=alpha*(hasModel?.6:1);c.strokeStyle=colour;c.lineWidth=width;const dx=Math.cos(angle)*length*.5,dy=Math.sin(angle)*length*.5;c.beginPath();c.moveTo(x-dx,y-dy);c.quadraticCurveTo(x,y-width*.2,x+dx,y+dy);c.stroke();}
 const cloudCount=Math.floor(state.count*(.58+a.level*.18));
 for(let i=0;i<cloudCount;i++){const u=(rand(i+seed%997)+time*.008)%1.2-.1,v=rand(i+73)*.62,x=u*w,y=v*h;const mass=Math.sin(u*9+Math.sin(v*11)+seed)*.6+Math.cos(v*17+u*3-time*.07)*.6;const alpha=Math.max(0,Math.min(.72,.12+mass*.35+a.level*.12));if(alpha<.08)continue;dab(x,y,9+rand(i+8)*26,.1+Math.sin(i+time*.03)*.15,5+rand(i+5)*13,colours[i%colours.length],alpha);if(i%3===0)dab(x+7,y+3,8,0,4,colours[(i+2)%colours.length],alpha*.65);}
 const waterTop=h*.59;for(let i=0;i<Math.floor(state.count*.52);i++){const u=rand(i+811),v=rand(i+433),x=u*w+Math.sin(time*.3+i)*4,y=waterTop+v*(h-waterTop),reflection=Math.abs(x-sx)<w*(.025+v*.11);dab(x,y,8+v*25+rand(i+29)*14,Math.sin(time*.35+i)*.045,2+v*5,reflection?(i%2?'#f6e8b6':'#fff6df'):['#b3c6ce','#b2bdd5','#e0d8c7','#8eadc3'][i%4],reflection?.28+a.level*.2:.24+rand(i+7)*.3);}
 if(a.pulse>.55&&state.pulse<=.55){state.ripples.push({start:time,x:w*(.2+rand(time+seed)*.6),y:h*(.68+rand(seed+time+5)*.2)});state.ripples=state.ripples.slice(-6);}state.pulse=a.pulse;
 state.ripples=state.ripples.filter(r=>time-r.start<4&&time>=r.start);for(const r of state.ripples){const age=time-r.start;for(let i=0;i<28;i++){const angle=i*TAU/28,radius=12+age*48;dab(r.x+Math.cos(angle)*radius,r.y+Math.sin(angle)*radius*.2,6+age*2,Math.atan2(Math.cos(angle)*.2,-Math.sin(angle)),1.5,'#fff0c5',(1-age/4)*.48);}}
 c.globalAlpha=1;return {backend:'canvas2d-monet',style:'monet',marks:state.count,frame_average_ms:+state.average.toFixed(2)};
}
