export const mappingDefaults={harmony:1,tension:1,dynamics:1,register:1,pedal:1,phrase:1};
const clamp=x=>Math.max(0,Math.min(1,x));
function hue(h,s=.8,l=.55){h=((h%360)+360)%360;const c=(1-Math.abs(2*l-1))*s,x=c*(1-Math.abs(h/60%2-1)),m=l-c/2;return [[c,x,0],[x,c,0],[0,c,x],[0,x,c],[x,0,c],[c,0,x]][Math.floor(h/60)%6].map(v=>v+m);}
function paletteHue(hex){const [r,g,b]=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255),hi=Math.max(r,g,b),lo=Math.min(r,g,b),d=hi-lo;if(!d)return 44;return ((hi===r?(g-b)/d:hi===g?(b-r)/d+2:(r-g)/d+4)*60+360)%360;}
export function pianoMapping(f,settings,seed,section={family:1,palette:['#2859cd','#e5b433']}){
 const tension=clamp(f.tension*settings.tension),dynamic=clamp(f.dynamics*settings.dynamics),base=paletteHue(section.palette[0])+(seed%17-8)+f.key*2*settings.harmony,colour=hue(base%360,.8-f.dissonance*.55*settings.harmony),secondary=hue((base+(f.quality==='dominant'?180:35+f.dissonance*100)*settings.harmony)%360,.8-f.dissonance*.5);
 return {audio:{level:dynamic,warmth:f.brightness,pulse:Math.max(f.pulse*.65,f.cadence),pitch:0},evolution:{seed,variant:seed%4096/650+f.phraseArc*.2,profile:{family:section.family,colours:section.palette,geometry:0,tempo:1},density:.65+dynamic*.75+f.density*.4,effect:tension>.4?2:4,strength:.2+tension*.7,symmetry:2,piano:{tension,register:(f.register-.5)*settings.register,pedal:clamp((f.pedalWash??f.pedal)*settings.pedal),colour,secondary,colourMix:clamp((f.quality==='dominant'?.7:f.dissonance*.8)*settings.harmony),bloom:dynamic,settle:f.cadence},breathRate:1/(2+(f.phraseSeconds-2)*settings.phrase)}};
}
export function localSection(name){const text=name.toLowerCase();if(/glass|mishima|格拉斯|三岛/.test(text))return {description:name,style:'narrative',family:4,palette:['#5b626b','#e6e6e2'],source:'local'};const water=/water|source|ondine|rain|arabesque|水|海|泉/.test(text),light=/flight|light|scriabin|sonata.*4|飞|光/.test(text);return {description:water?'Mirrored flowing water membranes with ink ripples':light?'Ascending luminous strokes unfolding into flight':'Breathing organic ink forms with spacious phrasing',family:water?1:light?3:4,palette:water?['#2859cd','#657075']:light?['#e5b433','#657075']:['#cbb677','#6f7982'],source:'local'};}
