import {musicFeatures,noteNames} from './music.mjs';
import {readMidi,midiAccess} from './midi.mjs';
import {pianoInput,pianoAudition} from './piano_audio.mjs';
import {pianoMapping,mappingDefaults,localSection} from './piano_mapping.mjs';
import {particleField} from './particles.mjs';
import {initial} from './parser.mjs';
import {pianoDemos} from './demos.mjs';
import {blenderLayer} from './blender.mjs';
const $=id=>document.getElementById(id),music=musicFeatures(),scene=initial(),step=1/120,settings={...mappingDefaults};let field=particleField($('stage')),seed=317,epoch=performance.now()/1000,sim=0,queueIndex=0,features=music.update(0),queue=[],sequence=0,player=null,playing=false,projector=null,midiStop=null,lastFrame=performance.now(),latency=null,pendingPaint=null,breathPhase=0,stats={},controller=null,sections=[],sectionIndex=0,prepared=new Map(),lastUI=0;
const audition=pianoAudition(),input=pianoInput((f,time)=>music.audio(f,time));
const zero=()=>$('zero').checked;
function section(){return sections[sectionIndex]??{name:'Romantic piano',...localSection('Romantic piano')}}
const blender=blenderLayer(()=>zero()?null:{piano:true,style:$('style').value,workStyle:{family:section().family,palette:section().palette},variation:{seed},audioMood:{level:features.dynamics,warmth:features.brightness}},$('blenderStatus'));
function status(text){$('status').textContent=text}
for(const [key,value] of Object.entries(settings)){const label=document.createElement('label');label.textContent=({harmony:'和声 / Harmony',tension:'张力 / Tension',dynamics:'力度 / Dynamics',register:'音区 / Register',pedal:'踏板 / Pedal',phrase:'乐句 / Phrase'})[key];const control=document.createElement('input');control.type='range';control.min=0;control.max=2;control.step=.05;control.value=value;control.dataset.mapping=key;control.oninput=()=>settings[key]=Number(control.value);label.append(control);$('mappings').append(label);}
for(const demo of pianoDemos){const option=document.createElement('option');option.value=demo.id;option.textContent=demo.name;$('demo').append(option);}
function enqueue(data,time,paintStamp=null){if(queueIndex){queue=queue.slice(queueIndex);queueIndex=0;}queue.push({data,time,order:sequence++,paintStamp});queue.sort((a,b)=>a.time-b.time||a.order-b.order);}
function reset(){music.reset();queue=[];queueIndex=0;sim=0;breathPhase=0;epoch=performance.now()/1000;pendingPaint=null;latency=null;features=music.update(0);audition.stop();}
function dispatch(data,time){music.midi(data,time);if($('audition').checked&&(data[0]&240)===144&&data[2])audition.note(data[1],data[2]);}
function stop(){playing=false;player=null;reset();$('play').textContent='播放 / Play';status('Stopped / 已停止');}
async function play(buffer){stop();try{player=readMidi(buffer);playing=true;queue=player.events.map((e,i)=>({...e,order:i}));sequence=queue.length;if($('audition').checked)await audition.start();epoch=performance.now()/1000;$('play').textContent='停止 / Stop';status(`MIDI file · ${player.events.length} events · ${player.duration.toFixed(1)} s`);}catch(e){status(e.message);}}
$('play').onclick=()=>{if(playing)return stop();const demo=pianoDemos.find(d=>d.id===$('demo').value);play(Uint8Array.from(atob(demo.base64),c=>c.charCodeAt(0)).buffer)};
$('file').onchange=async e=>{const file=e.target.files[0];if(file?.size>8_000_000)return status('MIDI file exceeds 8 MB');if(file)await play(await file.arrayBuffer())};
$('audition').onchange=async()=>{if($('audition').checked)await audition.start();else audition.stop()};
$('midi').onclick=async()=>{if(midiStop){midiStop();midiStop=null;music.reset();$('midi').textContent='连接 MIDI / Connect';return;}try{midiStop=await midiAccess((data,stamp)=>{const now=performance.now();enqueue(data,Math.max(0,stamp/1000-epoch),Math.min(now,stamp));},ports=>status(ports.length?ports.map(p=>p.name+' ('+p.state+')').join(', '):'No MIDI devices / 未发现设备'));$('midi').textContent='断开 MIDI / Disconnect';}catch(e){status(e.message)}};
$('audioInput').onclick=async()=>{if(input.active){input.stop();$('audioInput').textContent='麦克风 / Line-in';return;}$('audioInput').disabled=true;try{await input.start($('device').value);$('audioInput').textContent='停止音频 / Stop audio';const devices=await navigator.mediaDevices.enumerateDevices();$('device').replaceChildren();for(const d of devices.filter(d=>d.kind==='audioinput')){const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||'Audio input';$('device').append(o);}status('Audio analysis active; acoustic harmony is an estimate / 音频和声为估计值');}catch(e){input.stop();status(e.message)}finally{$('audioInput').disabled=false}};
$('device').onchange=async()=>{if(input.active){input.stop();try{await input.start($('device').value)}catch(e){status(e.message)}}};
$('seed').onchange=()=>{seed=Number($('seed').value)>>>0;$('seed').value=seed;stop()};
function setSections(){sections=$('setlist').value.split('\n').map(s=>s.trim()).filter(Boolean).slice(0,30).map(name=>({name,...(prepared.get(name)??localSection(name))}));sectionIndex=0;$('section').replaceChildren();for(const [i,item] of sections.entries()){const option=document.createElement('option');option.value=i;option.textContent=item.name;$('section').append(option);}showSection();}
function showSection(){$('brief').textContent=section().description+' · '+section().source;}
$('applySetlist').onclick=setSections;$('section').onchange=()=>{sectionIndex=Number($('section').value);showSection()};$('next').onclick=()=>{sectionIndex=(sectionIndex+1)%Math.max(1,sections.length);$('section').value=sectionIndex;showSection()};
$('zero').onchange=()=>{controller?.abort();$('preload').disabled=zero();if(zero()){document.querySelectorAll('video').forEach(v=>{v.pause();v.removeAttribute('src');v.classList.remove('visible')});$('blenderStatus').textContent='Zero-AI · tiers 2/3 disabled';prepared.clear();setSections();status('Zero-AI: local rules + MIDI + seed / 本地确定性演奏')}else status('Optional backend enabled; preload before performing / 可预加载谱单')};
$('preload').onclick=async()=>{if(zero())return;controller?.abort();controller=new AbortController();setSections();$('preload').disabled=true;try{for(const item of sections){if(zero())break;status('Preparing / 预加载: '+item.name);const response=await fetch('./api/section',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({piece:item.name,style:$('style').value}),signal:controller.signal});if(!response.ok)throw Error('Backend offline / 后端离线; local section briefs retained');const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',generated=false;while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value??new Uint8Array(),{stream:!done});let at;while((at=buffer.indexOf('\n'))>=0){const text=buffer.slice(0,at);buffer=buffer.slice(at+1);if(!text.trim())continue;const data=JSON.parse(text);if(data.brief){generated=true;prepared.set(item.name,{...data.brief,source:'GPT-6 (preloaded)'});Object.assign(item,prepared.get(item.name));}if(data.error)throw Error(data.error);}if(done)break;}if(!generated)throw Error('Section unavailable; local brief retained / 保留本地段落');}showSection();status('Setlist ready / 谱单已就绪')}catch(e){status(e.message)}finally{$('preload').disabled=zero()}};
function saved(){try{return JSON.parse(localStorage.getItem('voice-piano-pieces')||'{}')}catch{return {}}}
function listPresets(){$('presets').replaceChildren(new Option('选择已保存作品 / Saved pieces',''));for(const name of Object.keys(saved()))$('presets').append(new Option(name,name));}
$('savePreset').onclick=()=>{const all=saved(),name=$('piece').value.trim()||'Piano piece';all[name]={settings:{...settings},seed,style:$('style').value,setlist:$('setlist').value};try{localStorage.setItem('voice-piano-pieces',JSON.stringify(all));listPresets();status('Piece preset saved / 作品预设已保存')}catch(e){status(e.message)}};
$('presets').onchange=()=>{const p=saved()[$('presets').value];if(!p)return;for(const key of Object.keys(settings)){const v=Number(p.settings?.[key]);settings[key]=Number.isFinite(v)?Math.max(0,Math.min(2,v)):1;document.querySelector(`[data-mapping="${key}"]`).value=settings[key];}seed=Number(p.seed)>>>0;$('seed').value=seed;$('style').value=p.style==='moyers'?'moyers':'fusion';$('setlist').value=String(p.setlist??'');setSections();stop()};
$('exportPreset').onclick=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify({seed,settings,style:$('style').value,sections},null,2)],{type:'application/json'}));a.href=url;a.download='piano-piece.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('project').onclick=()=>{if(projector&&!projector.closed){projector.focus();return;}projector=window.open('./piano_projector.html','_blank','width=1280,height=720');if(!projector)status('Allow the projector popup / 请允许投影窗口')};
function performanceMode(){document.body.classList.toggle('performance');if(document.body.classList.contains('performance'))document.documentElement.requestFullscreen?.().catch(()=>{});else if(document.fullscreenElement)document.exitFullscreen?.();}$('perform').onclick=performanceMode;
const keys={a:60,w:61,s:62,e:63,d:64,f:65,t:66,g:67,y:68,h:69,u:70,j:71,k:72};
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||e.repeat)return;if(e.key.toLowerCase()==='p')return performanceMode();if(e.code==='Space'){e.preventDefault();$('play').click();return;}if(keys[e.key]!==undefined)enqueue([144,keys[e.key],95],performance.now()/1000-epoch,performance.now())});document.addEventListener('keyup',e=>{if(keys[e.key]!==undefined)enqueue([128,keys[e.key],0],performance.now()/1000-epoch)});
function frame(ms){const dt=Math.min(.05,(ms-lastFrame)/1000);lastFrame=ms;const target=(ms/1000-epoch);input.update(target);let steps=0;while(sim+step<=target&&steps++<240){sim+=step;while(queueIndex<queue.length&&queue[queueIndex].time<=sim){const e=queue[queueIndex++];dispatch(e.data,e.time);if(e.paintStamp!==null&&e.paintStamp!==undefined)pendingPaint=pendingPaint===null?e.paintStamp:Math.min(pendingPaint,e.paintStamp);}features=music.update(sim);breathPhase+=step/(2+(features.phraseSeconds-2)*settings.phrase);}
 if(steps>=240){sim=target;status('Background catch-up; latency unavailable / 后台恢复');pendingPaint=null;}
 const mapped=pianoMapping(features,settings,seed,section());mapped.evolution.clock=sim;mapped.evolution.deterministic=zero();mapped.evolution.breathRate=sim?breathPhase/sim:.125;
 if(field?.needsRebuild){field.canvas.remove();field=particleField($('stage'));}if(field)stats=field.draw(sim,dt,scene,mapped.audio,blender.visible,mapped.evolution,$('style').value)??{};
 if(pendingPaint!==null){latency=document.hidden?null:Math.max(0,performance.now()-pendingPaint);pendingPaint=null;}
 if(projector&&!projector.closed)projector.postMessage({type:'piano-frame',time:sim,dt,scene,audio:mapped.audio,evolution:mapped.evolution,style:$('style').value,loop:!zero()&&document.querySelector('video.blender.visible')?.currentSrc?{src:document.querySelector('video.blender.visible').currentSrc,time:document.querySelector('video.blender.visible').currentTime}:null},location.origin==='null'?'*':location.origin);
 if(ms-lastUI>150){lastUI=ms;$('features').textContent=JSON.stringify({...features,chroma:features.chroma.map(v=>+v.toFixed(2)),key:noteNames[features.key]+' '+features.mode,chord:noteNames[features.root]+' '+features.quality},null,2);$('timing').textContent=JSON.stringify({midi_to_render_ms:latency===null?null:+latency.toFixed(2),frame_ms:stats.frame_average_ms,particles:stats.particles,mode:zero()?'Zero-AI':'Prepared sections',time:+sim.toFixed(2)},null,2);}
 if(playing&&sim>player.duration+.5){playing=false;player=null;$('play').textContent='播放 / Play';music.reset();status('Demo complete / 示范结束');}requestAnimationFrame(frame);}
window.piano={enqueue,midi(data){const now=performance.now();enqueue(data,Math.max(0,now/1000-epoch),now)},get features(){return features},get stats(){return stats},get latency(){return latency},get time(){return sim},get settings(){return settings},reset,play};
addEventListener('pagehide',()=>{midiStop?.();input.stop();audition.stop();controller?.abort()});listPresets();setSections();requestAnimationFrame(frame);
