const sourceLink=url=>/^https:\/\//.test(url??'')||/^http:\/\/piano-midi\.de\//.test(url??'');
import {localSection} from './piano_mapping.mjs';
export function repertoireBrief(item){const brief=localSection(item.title),f=item.fingerprint;if(!f)return brief;const notes=['C','C♯','D','E♭','E','F','F♯','G','A♭','A','B♭','B'],colours=['#c89e45','#ba814b','#d96d51','#b66677','#8b74be','#5778c8','#3c9bc7','#3badb4','#55af87','#7aa94d','#b0ab50','#c9b360'],key=Math.max(0,notes.indexOf(f.key.split(' ')[0])),tension=f.tension_curve.reduce((a,b)=>a+b,0)/Math.max(1,f.tension_curve.length);return {...brief,palette:[colours[key],tension>.45?colours[(key+6)%12]:'#73828a'],description:item.title+' · '+f.key+' (estimated) · '+item.mood,source:'MIDI fingerprint estimate'};}
export function repertoirePanel(container,{play,add,select=()=>{}}){
 const search=document.createElement('input'),era=document.createElement('select'),mood=document.createElement('select'),duration=document.createElement('select'),list=document.createElement('div'),status=document.createElement('p');search.placeholder='作曲家 / 标题 / Opus';search.setAttribute('aria-label','Repertoire search');era.setAttribute('aria-label','Era');mood.setAttribute('aria-label','Mood');duration.setAttribute('aria-label','Duration');
 era.append(...['All eras','Baroque','Classical','Romantic','Impressionist','Modern'].map(v=>new Option(v,v)));mood.append(...['All moods','calm','flowing','intense','unanalysed'].map(v=>new Option(v,v)));duration.append(...[['Any duration','0'],['< 5 minutes','300'],['< 15 minutes','900'],['15+ minutes','-900']].map(([l,v])=>new Option(l,v)));const sources=document.createElement('details');sources.append(Object.assign(document.createElement('summary'),{textContent:'来源与许可 / Sources & licences'}));container.append(search,era,mood,duration,status,sources,list);fetch('./repertoire/sources.json').then(r=>r.json()).then(rows=>{for(const row of rows){if(!sourceLink(row.url))continue;const p=document.createElement('p'),a=document.createElement('a');a.href=row.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=row.name;p.append(a,document.createTextNode(' · '+row.license+' · '+row.policy));sources.append(p);}}).catch(()=>{});let items=[],selected=null,program=[],programIndex=-1,pendingIds=[];const perform=document.createElement('button'),stop=document.createElement('button');perform.textContent='演奏谱单 / Play program';stop.textContent='停止续播 / End program';container.insertBefore(perform,status);container.insertBefore(stop,status);perform.onclick=()=>{programIndex=0;if(program.length)load(program[0]);};stop.onclick=()=>{programIndex=-1;status.textContent='Program continuation OFF';};
 async function load(item){select(item);selected=item.id;if(!item.local_path&&!item.midi_url){status.textContent='尚未下载；请使用乐谱/来源链接或运行 fetch.py / Not downloaded';return;}try{let response;if(item.local_path)response=await fetch('./repertoire/'+item.local_path);else{try{response=await fetch('./api/repertoire/'+encodeURIComponent(item.id));if(!response.ok)throw Error('No local downloader');}catch{response=await fetch(item.midi_url);}}if(!response.ok)throw Error('MIDI unavailable on this host');const buffer=await response.arrayBuffer();if(buffer.byteLength>8000000)throw Error('MIDI exceeds 8 MB');await play(buffer,item);status.textContent=item.title+' · '+item.license;}catch(e){status.textContent=e.message;}}
 function restore(ids){pendingIds=Array.isArray(ids)?ids.slice(0,100):[];program=pendingIds.map(id=>items.find(p=>p.id===id)).filter(Boolean);programIndex=-1;perform.textContent='演奏谱单 / Play program ('+program.length+')';}
 const fold=s=>s.toLowerCase().normalize('NFD').replace(/\p{M}/gu,'');
 function render(){const term=fold(search.value),limit=Number(duration.value),filtered=items.filter(p=>fold(p.composer+' '+p.title+' '+p.opus).includes(term)&&(era.value==='All eras'||p.era===era.value)&&(mood.value==='All moods'||p.mood===mood.value)&&(!limit||p.duration&&(limit>0?p.duration<limit:p.duration>=-limit))).sort((a,b)=>Number(!!b.local_path)-Number(!!a.local_path));status.textContent=filtered.length+' 条 / matches · '+items.filter(p=>p.local_path).length+' 已下载 / downloaded';list.replaceChildren();for(const p of filtered.slice(0,40)){const row=document.createElement('div');row.style.cssText='padding:8px 0;border-bottom:1px solid #444';const title=document.createElement('div');title.textContent=p.composer+' — '+p.title;const detail=document.createElement('small');detail.textContent=[p.opus,p.key,p.duration?Math.round(p.duration/60)+' min':'duration unknown',p.license,p.local_path?'已下载 / local':p.midi_url?'按需下载 / download on play':'乐谱或来源 / source'].filter(Boolean).join(' · ');const button=document.createElement('button');button.textContent='播放 / Play';button.disabled=!p.local_path&&!p.midi_url;button.onclick=()=>{programIndex=-1;load(p)};const enqueue=document.createElement('button');enqueue.textContent='加入谱单 / Setlist';enqueue.onclick=()=>{selected=p.id;select(p);program.push(p);add(p);perform.textContent='演奏谱单 / Play program ('+program.length+')'};const link=document.createElement('a');link.textContent=' 乐谱 / Source';link.href=/^https:\/\//.test(p.score_url??'')?p.score_url:p.source_url;link.target='_blank';link.rel='noopener noreferrer';row.append(title,detail,button,enqueue,link);list.append(row);}if(filtered.length>40){const more=document.createElement('p');more.textContent='显示前 40 条；输入关键词缩小范围 / Refine search';list.append(more);}}
 for(const control of [search,era,mood,duration])control.oninput=control.onchange=render;
 fetch('./repertoire/index.json').then(r=>{if(!r.ok)throw Error('Catalogue unavailable');return r.json()}).then(data=>{items=data.items.filter(p=>typeof p.id==='string'&&typeof p.title==='string'&&(!p.local_path||/^(curated|local)\/[A-Za-z0-9_./-]+\.(mid|midi)$/.test(p.local_path)&&!p.local_path.includes('..'))&&sourceLink(p.source_url));restore(pendingIds);render()}).catch(()=>status.textContent='曲库未加载；仍可播放内置示范或导入 MIDI / Serve this page to load the catalogue');
 return {restore,cancel(){programIndex=-1;},finish(){if(programIndex>=0&&++programIndex<program.length)load(program[programIndex]);else programIndex=-1;},get programIds(){return program.map(p=>p.id)},get selected(){return selected},get items(){return items},load};
}
