import {cinematicGraph} from './cinematic.mjs';
import {features} from './audio.mjs';
// Original electroacoustic synthesis: no recordings, samples, model training or external audio.
export function soundGraph(context,destination=context.destination){
 const master=context.createGain(),filter=context.createBiquadFilter(),pan=context.createStereoPanner(),limiter=context.createDynamicsCompressor();
 master.gain.value=0;filter.type='lowpass';filter.frequency.value=900;filter.Q.value=.7;limiter.threshold.value=-15;limiter.ratio.value=5;filter.connect(pan);pan.connect(master);master.connect(limiter);limiter.connect(destination);const analyser=context.createAnalyser();analyser.fftSize=2048;limiter.connect(analyser);
 const voices=[1,1.498,2.003,4.007].map((ratio,i)=>{const o=context.createOscillator(),g=context.createGain();o.type=i===1?'triangle':'sine';o.frequency.value=55*ratio;g.gain.value=i===3?.13:i?.07:.19;o.connect(g);g.connect(filter);o.start();return {o,g,ratio};});
 const cue=context.createOscillator(),cueGain=context.createGain();cue.frequency.setValueAtTime(440,context.currentTime);cue.frequency.exponentialRampToValueAtTime(330,context.currentTime+.65);cueGain.gain.setValueAtTime(0,context.currentTime);cueGain.gain.linearRampToValueAtTime(.35,context.currentTime+.025);cueGain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+.85);cue.connect(cueGain);cueGain.connect(filter);cue.start();cue.stop(context.currentTime+.9);
 const noise=context.createBufferSource(),noiseFilter=context.createBiquadFilter(),noiseGain=context.createGain(),buffer=context.createBuffer(1,context.sampleRate*3,context.sampleRate),data=buffer.getChannelData(0);let seed=317;
 for(let i=0;i<data.length;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;data[i]=(seed/2147483648-1)*Math.min(1,i/240,(data.length-i)/240);}noise.buffer=buffer;noise.loop=true;noiseFilter.type='bandpass';noiseFilter.frequency.value=600;noiseFilter.Q.value=2;noiseGain.gain.value=.04;noise.connect(noiseFilter);noiseFilter.connect(noiseGain);noiseGain.connect(filter);noise.start();
 let lastBurst=-10,oldPulse=0;const sources=new Set();
 function update(t,a,family=1,variant=0,volume=.12,effect=0){const at=context.currentTime,root=[49,55,36.71,82.41,65.41][family]??55;const pitch=a.pitch>70&&a.pitch<900?a.pitch/Math.pow(2,Math.floor(Math.log2(a.pitch/root))):root;
 voices.forEach(({o,g,ratio},i)=>{o.frequency.setTargetAtTime((root*.8+pitch*.2)*ratio*(1+Math.sin(t*(effect===0?.25:.11)+i+variant)*.006),at,.3);const base=i===3?.13:i?.07:.19,tremolo=effect===1?.7+.3*Math.sin(t*(1.4+i*.4)+variant):1;g.gain.setTargetAtTime(base*tremolo*(effect===2?.4:1),at,.4);});filter.Q.setTargetAtTime(effect===3?4:.7,at,.8);filter.frequency.setTargetAtTime(400+a.warmth*2400+a.level*1000+Math.sin(t*.2+variant)*110,at,.15);noiseFilter.frequency.setTargetAtTime(200+family*190+a.warmth*1100,at,.2);noiseGain.gain.setTargetAtTime(.015+a.level*.07+(1+Math.sin(t*.3+variant))*.012+(effect===2?.07:0),at,.2);master.gain.setTargetAtTime(volume*(.65+a.level*.35),at,.12);pan.pan.setTargetAtTime(Math.sin(t*.1+variant)*.45,at,.15);
 const onset=a.pulse>.6&&oldPulse<=.6,ambient=t-lastBurst>(effect===2?.38:effect===1?1.2:3.8)+(Math.sin(variant)*.15);
 if((onset||ambient)&&t-lastBurst>.18){lastBurst=t;const o=context.createOscillator(),g=context.createGain();o.type=family===0?'triangle':'sine';o.frequency.setValueAtTime(root*(effect===1?[2,2.5,3,4,6][Math.floor(t+variant)%5]:family===3?8:3)+a.warmth*90,at);o.frequency.exponentialRampToValueAtTime(root*1.5,at+.8);g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(onset?.12:.035,at+.012);g.gain.exponentialRampToValueAtTime(.0001,at+1.2);o.connect(g);g.connect(filter);o.start(at);o.stop(at+1.3);sources.add(o);o.onended=()=>{sources.delete(o);o.disconnect();g.disconnect();};}
 oldPulse=a.pulse;
 }
 function close(){for(const {o} of voices)o.stop();noise.stop();for(const source of sources)source.stop();master.disconnect();}
 return {update,close,master,analyser};
}
export function liveSound(onStatus){
 let context,graph,busy=false,enabled=false,mode='electroacoustic',selectedSeed=317,last=0,old={},samples,spectrum;const state={rms:0,centroid:0,pitch:0,level:0,warmth:0,pulse:0,active:false,source:'synthesis'};
 return {get mode(){return mode},get clock(){return graph?.time??0},get breathRate(){return graph?.breathRate??.125},setMode(next){mode=next==='cinematic'?'cinematic':'electroacoustic';if(enabled){graph.close();graph=mode==='cinematic'?cinematicGraph(context,{seed:selectedSeed}):soundGraph(context);old={};state.pulse=0;}},get enabled(){return enabled},get rms(){return state.rms},async toggle(){if(busy)return enabled;busy=true;try{if(enabled){enabled=false;graph.close();graph=null;await context.close();context=null;return false;}context=new AudioContext();await context.resume();graph=mode==='cinematic'?cinematicGraph(context,{seed:selectedSeed}):soundGraph(context);samples=new Float32Array(2048);spectrum=new Float32Array(1024);enabled=true;onStatus(mode==='cinematic'?'Cinematic · 大提琴与钢琴氛围 / Cello + piano atmosphere':'声音已开启 · 应能听到测试音 / Sound on · test tone');return true;}finally{busy=false;}},sample(t,dt){state.pulse*=Math.exp(-dt*4);if(graph&&t-last>80){last=t;graph.analyser.getFloatTimeDomainData(samples);graph.analyser.getFloatFrequencyData(spectrum);const next=features(samples,spectrum,context.sampleRate,old);if(next.rms>(old.rms??0)*1.65&&next.rms>.004)state.pulse=1;old=next;Object.assign(state,next,{level:Math.min(1,next.rms*35),active:true});}state.pulse=Math.max(state.pulse,graph?.pulse??0);return state;},update(t,a,family,variant,volume,effect,seed=317,parts=3){selectedSeed=seed;if(enabled){if(mode==='cinematic'){graph.setSeed(seed);graph.update(graph.time,a,volume,variant,parts);}else graph.update(t,a,family,variant,volume,effect)}},stop(){if(enabled){enabled=false;graph.close();context.close();}}};
}
