import {musicFeatures} from './music.mjs';
import {pianoMapping,mappingDefaults,localSection} from './piano_mapping.mjs';
import {readMidi,midiAccess} from './midi.mjs';
import {pianoInput} from './piano_audio.mjs';
import {pianoDemos} from './demos.mjs';
import {parse,apply} from './parser.mjs';
import {blenderLayer} from './blender.mjs';
export function workbench({clock,scene,seed,save,onMidi,onInput}){
 const $=id=>document.getElementById(id),music=musicFeatures(),settings={...mappingDefaults};let queue=[],projector,recognition,midiStop,controller,history=[],brief=localSection('water'),lastUI=0;
 const input=pianoInput((f)=>music.audio(f,clock()));
 const status=text=>$('benchStatus').textContent=text;
 const zero=()=>$('zero').checked;
 const blender=blenderLayer(()=>zero()?null:{...scene,style:$('style').value,monet:$('monetBlend').checked,variation:{seed:seed()},workStyle:{family:brief.family,palette:brief.palette}},$('blenderStatus'));
 function enqueue(data,time){queue.push({data,time});queue.sort((a,b)=>a.time-b.time);}
 function event(e){if(e.kind==='pedal')enqueue([176,64,e.down?90:0],e.time);if(e.kind==='piano'){enqueue([144,e.midi,Math.round(e.strength*110)],e.time);enqueue([128,e.midi,0],e.time+(e.duration??.7));}}
 function describe(text){$('transcript').textContent=text;const edits=parse(text);if(edits.some(e=>e.command==='save'))save();else if(edits.some(e=>e.command==='undo')){if(history.length)Object.assign(scene,history.pop());}else{history.push(structuredClone(scene));history=history.slice(-30);Object.assign(scene,apply(scene,edits));}status('语义已更新 / Scene updated');}
 $('description').onsubmit=e=>{e.preventDefault();describe($('text').value)};
 $('speech').onclick=()=>{if(recognition){recognition.stop();recognition=null;return;}const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech)return status('请用文字输入 / Speech unavailable');recognition=new Speech();recognition.lang=$('language').value;recognition.continuous=true;recognition.interimResults=true;recognition.onresult=e=>{let text='';for(let i=e.resultIndex;i<e.results.length;i++){text+=e.results[i][0].transcript;if(e.results[i].isFinal)describe(e.results[i][0].transcript);}$('transcript').textContent=text;};recognition.onerror=e=>status(e.error);recognition.onend=()=>{recognition=null;$('speech').textContent='语音 / Speech';};recognition.start();$('speech').textContent='停止语音 / Stop speech';};
 $('midiInput').onclick=async()=>{onInput();if(midiStop){midiStop();midiStop=null;music.reset();status('MIDI input OFF');return;}try{midiStop=await midiAccess(data=>{enqueue([...data],clock());onMidi(data)},ports=>status('MIDI input: '+ports.map(p=>p.name).join(', ')));}catch(e){status(e.message)}};
 $('lineInput').onclick=async()=>{onInput();try{if(input.active){input.stop();status('Line-in OFF');}else{await input.start();status('钢琴音频分析开启 / Piano analysis ON');}}catch(e){status(e.message)}};
 for(const [key,value] of Object.entries(settings)){const label=document.createElement('label');label.textContent=key;const control=document.createElement('input');control.type='range';control.min=0;control.max=2;control.step=.05;control.value=value;control.oninput=()=>settings[key]=Number(control.value);control.dataset.mapping=key;label.append(control);$('mappings').append(label);}
 for(const demo of pianoDemos)$('demo').append(new Option(demo.name,demo.id));
 let fileEvents=[],fileIndex=0,fileStart=0;
 function play(buffer){onInput();const midi=readMidi(buffer);fileEvents=midi.events;fileIndex=0;fileStart=clock();music.reset();queue=[];status('MIDI file: '+midi.duration.toFixed(1)+' s');}
 $('demoPlay').onclick=()=>{try{const demo=pianoDemos.find(d=>d.id===$('demo').value);play(Uint8Array.from(atob(demo.base64),c=>c.charCodeAt(0)).buffer);}catch(e){status(e.message)}};
 $('midiFile').onchange=async()=>{const f=$('midiFile').files[0];try{if(f?.size>8000000)throw Error('MIDI limit: 8 MB');if(f)play(await f.arrayBuffer());}catch(e){status(e.message)}};
 $('demoStop').onclick=()=>{fileEvents=[];queue=[];music.reset();onMidi([176,123,0]);onMidi([176,64,0]);status('File stopped')};
 $('project').onclick=()=>{projector=window.open('./piano_projector.html','_blank','width=1280,height=720');if(!projector)status('请允许投影窗口 / Allow popup')};
 let sections=[];
 function setlist(){sections=$('setlist').value.split('\n').map(n=>n.trim()).filter(Boolean).slice(0,30).map(name=>({name,...localSection(name)}));$('section').replaceChildren(...sections.map((s,i)=>new Option(s.name,i)));brief=sections[0]??localSection('water');}
 $('applySetlist').onclick=setlist;$('section').onchange=()=>brief=sections[Number($('section').value)]??brief;
 async function request(path,body,handle){controller?.abort();controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);try{const res=await fetch('./api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:controller.signal});if(!res.ok)throw Error('Backend offline / 后端离线');const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value??new Uint8Array(),{stream:!done});let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i);buffer=buffer.slice(i+1);if(line.trim()&&!zero())handle(JSON.parse(line));}if(done)break;}}catch(e){status('Backend offline / 后端离线 · '+e.message)}finally{clearTimeout(timer)}}
 $('preload').onclick=async()=>{if(zero())return;setlist();for(const item of sections){if(zero())break;await request('section',{piece:item.name,style:$('style').value==='fusion'&&$('monetBlend').checked?'fusion+monet':$('style').value},d=>{if(d.brief)Object.assign(item,d.brief);if(d.error)status(d.error)});}brief=sections[Number($('section').value)]??brief;};
 $('generate').onclick=()=>{if(zero())return;const start=performance.now();request('scene',{transcript:$('text').value,scene:{...scene,style:$('style').value,monet:$('monetBlend').checked}},d=>{if(d.html){$('generated').srcdoc='<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; img-src data:">'+d.html;status('GPT-6 · '+Math.round(performance.now()-start)+' ms');}if(d.error)status(d.error)});};
 $('zero').onchange=()=>{controller?.abort();$('preload').disabled=$('generate').disabled=zero();if(zero()){$('generated').srcdoc='';document.querySelectorAll('video.blender').forEach(v=>{v.pause();v.classList.remove('visible')});setlist();}$('blenderStatus').textContent=zero()?'Zero-AI · tiers 2/3 OFF':'后台待命 / Backend standby';};
 $('savePiece').onclick=()=>{const p={seed:seed(),settings,style:$('style').value,monet:$('monetBlend').checked,setlist:$('setlist').value,sound:$('soundMode').value,parts:$('pianoParts').value};try{localStorage.setItem('voice-performer-piece',JSON.stringify(p));status('作品已保存 / Piece saved')}catch(e){status(e.message)}};
 $('loadPiece').onclick=()=>{try{const p=JSON.parse(localStorage.getItem('voice-performer-piece'));if(!p)return;for(const k of Object.keys(settings)){settings[k]=Math.max(0,Math.min(2,(Number.isFinite(Number(p.settings?.[k]))?Number(p.settings[k]):1)));document.querySelector('[data-mapping="'+k+'"]').value=settings[k];}$('seed').value=String(Number(p.seed)>>>0);$('seed').dispatchEvent(new Event('change'));$('style').value=p.style;$('monetBlend').checked=!!p.monet;$('setlist').value=p.setlist;$('soundMode').value=p.sound;$('soundMode').dispatchEvent(new Event('change'));$('pianoParts').value=p.parts;setlist();}catch(e){status(e.message)}};
 addEventListener('pagehide',()=>{recognition?.stop();midiStop?.();input.stop();controller?.abort()});setlist();
 return {event,reset(){queue=[];music.reset();fileEvents=[];},get blender(){return blender.visible},frame(time,dt,base,a){input.update(time);while(fileIndex<fileEvents.length&&fileEvents[fileIndex].time<=time-fileStart){const e=fileEvents[fileIndex++];enqueue(e.data,fileStart+e.time);onMidi(e.data);}while(queue.length&&queue[0].time<=time){const e=queue.shift();music.midi(e.data,e.time);}const f=music.update(time),mapped=pianoMapping(f,settings,seed(),brief);const active=f.polyphony>0||time-f.lastInput<3;const evolution=active?{...base,...mapped.evolution,clock:time,deterministic:zero()}:base;const audio=active?{...a,level:Math.max(a.level,mapped.audio.level),pulse:Math.max(a.pulse,mapped.audio.pulse)}:a;if(projector&&!projector.closed)projector.postMessage({type:'piano-frame',time,dt,scene,audio,evolution,style:$('style').value,monet:$('monetBlend').checked,loop:!zero()&&document.querySelector('video.blender.visible')?.currentSrc?{src:document.querySelector('video.blender.visible').currentSrc,time:document.querySelector('video.blender.visible').currentTime}:null},location.protocol==='file:'?'*':location.origin);if(time-lastUI>.2){lastUI=time;$('musicFeatures').textContent=JSON.stringify({key:f.key,chord:f.quality,tension:+f.tension.toFixed(2),notes:f.polyphony,pedal:f.pedal},null,2);}return {evolution,audio};}};
}
