import {repertoirePanel,repertoireBrief} from './repertoire.mjs';
import {pluginLayer,curatedPlugins,validatePlugin} from './plugins.mjs';
import {connectomeLayer} from './connectome.mjs';
import {musicFeatures} from './music.mjs';
import {pianoMapping,mappingDefaults,localSection} from './piano_mapping.mjs';
import {readMidi,midiAccess} from './midi.mjs';
import {pianoInput} from './piano_audio.mjs';
import {pianoDemos} from './demos.mjs';
import {parse,apply} from './parser.mjs';
import {blenderLayer} from './blender.mjs';
export function workbench({clock,scene,seed,save,onMidi,onInput,startAudio,startSpeechAudio,onPlan}){
 const $=id=>document.getElementById(id),music=musicFeatures(),settings={...mappingDefaults};let queue=[],recognition,midiStop,controller,history=[],brief=localSection('water'),lastUI=0,pendingSpeech=null,pendingMidi=null,paintLatency=null,midiLatency=null,modelLatency=null,lastMetrics=0,stopSpeechAudio=null;
 const plugins=pluginLayer($('stage'),text=>$('pluginStatus').textContent=text),connectome=connectomeLayer($('stage'));
 const input=pianoInput((f)=>music.audio(f,clock()));
 const status=text=>$('benchStatus').textContent=text;
 const zero=()=>$('zero').checked;
 const blender=blenderLayer(()=>zero()?null:{...scene,style:$('style').value,monet:$('monetBlend').checked,variation:{seed:seed()},workStyle:{family:brief.family,palette:brief.palette}},$('blenderStatus'));
 function enqueue(data,time){queue.push({data,time});queue.sort((a,b)=>a.time-b.time);}
 function event(e){if(e.kind==='pedal')enqueue([176,64,e.down?90:0],e.time);if(e.kind==='piano'){enqueue([144,e.midi,Math.round(e.strength*110)],e.time);enqueue([128,e.midi,0],e.time+(e.duration??.7));}}
 function describe(text){pendingSpeech=performance.now();$('transcript').textContent=text;const edits=parse(text);if(edits.some(e=>e.command==='save'))save();else if(edits.some(e=>e.command==='undo')){if(history.length)Object.assign(scene,history.pop());}else{history.push(structuredClone(scene));history=history.slice(-30);Object.assign(scene,apply(scene,edits));}status('语义已更新 / Scene updated');}
 $('description').onsubmit=e=>{e.preventDefault();describe($('text').value)};
 $('speech').onclick=async()=>{if(recognition){recognition.stop();recognition=null;return;}const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech)return status('请用文字输入 / Speech unavailable');$('speech').disabled=true;try{stopSpeechAudio=await startSpeechAudio();}catch(e){status(e.message);return;}finally{$('speech').disabled=false;}recognition=new Speech();recognition.lang=$('language').value;recognition.continuous=true;recognition.interimResults=true;recognition.onresult=e=>{let text='';for(let i=e.resultIndex;i<e.results.length;i++){text+=e.results[i][0].transcript;if(e.results[i].isFinal)describe(e.results[i][0].transcript);}$('transcript').textContent=text;};recognition.onerror=e=>status(e.error);recognition.onend=()=>{stopSpeechAudio?.();stopSpeechAudio=null;recognition=null;$('speech').textContent='语音 / Speech';};try{recognition.start();$('speech').textContent='停止语音 / Stop speech';}catch(e){stopSpeechAudio?.();stopSpeechAudio=null;recognition=null;status(e.message);}};
 $('midiInput').onclick=async(keepPerformer=false)=>{if(!keepPerformer)onInput();if(midiStop){midiStop();midiStop=null;music.reset();status('MIDI input OFF');return;}try{midiStop=await midiAccess((data,stamp)=>{pendingMidi=Math.min(performance.now(),stamp??performance.now());enqueue([...data],clock());onMidi(data,'device')},ports=>status('MIDI input: '+ports.map(p=>p.name).join(', ')));}catch(e){status(e.message)}};
 $('lineInput').onclick=async()=>{onInput();try{if(input.active){input.stop();status('Line-in OFF');}else{await input.start();status('钢琴音频分析开启 / Piano analysis ON');}}catch(e){status(e.message)}};
 for(const [key,value] of Object.entries(settings)){const label=document.createElement('label');label.textContent=key;const control=document.createElement('input');control.type='range';control.min=0;control.max=2;control.step=.05;control.value=value;control.oninput=()=>settings[key]=Number(control.value);control.dataset.mapping=key;label.append(control);$('mappings').append(label);}
 for(const demo of pianoDemos)$('demo').append(new Option(demo.name,demo.id));
 let directed=null,directedNext=null,directedStart=0,directedIndex=0;
 let fileEvents=[],fileIndex=0,fileStart=0,fileEnd=null;
 function play(buffer){onInput();onMidi([176,64,0]);onMidi([176,123,0]);const midi=readMidi(buffer);fileEvents=midi.events;fileIndex=0;fileStart=clock();fileEnd=fileStart+midi.duration+.5;music.reset();queue=[];status('MIDI file: '+midi.duration.toFixed(1)+' s');}
 $('demoPlay').onclick=()=>{try{const demo=pianoDemos.find(d=>d.id===$('demo').value);play(Uint8Array.from(atob(demo.base64),c=>c.charCodeAt(0)).buffer);}catch(e){status(e.message)}};
 $('midiFile').onchange=async()=>{const f=$('midiFile').files[0];try{if(f?.size>8000000)throw Error('MIDI limit: 8 MB');if(f)play(await f.arrayBuffer());}catch(e){status(e.message)}};
 $('demoStop').onclick=()=>{library.cancel();fileEnd=null;fileEvents=[];queue=[];music.reset();onMidi([176,123,0]);onMidi([176,64,0]);status('File stopped')};
 let libraryId=null;const library=repertoirePanel($('repertoire'),{play:async(buffer,item)=>{await startAudio();libraryId=item.id;play(buffer);},select:item=>{libraryId=item.id;brief=repertoireBrief(item);},add:item=>{$('setlist').value+='\n'+item.composer+' — '+item.title;setlist();}});
 let sections=[];
 function setlist(){sections=$('setlist').value.split('\n').map(n=>n.trim()).filter(Boolean).slice(0,30).map(name=>({name,...localSection(name)}));$('section').replaceChildren(...sections.map((s,i)=>new Option(s.name,i)));brief=sections[0]??localSection('water');}
 $('applySetlist').onclick=setlist;$('section').onchange=()=>brief=sections[Number($('section').value)]??brief;
 async function request(path,body,handle){controller?.abort();controller=new AbortController();const timer=setTimeout(()=>controller.abort(),path==='plugin'?50000:30000);try{const res=await fetch('./api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:controller.signal});if(!res.ok)throw Error('Backend offline / 后端离线');const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value??new Uint8Array(),{stream:!done});let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i);buffer=buffer.slice(i+1);if(line.trim()&&!zero())handle(JSON.parse(line));}if(done)break;}}catch(e){status('Backend offline / 后端离线 · '+e.message)}finally{clearTimeout(timer)}}

 let gallery=[];try{gallery=JSON.parse(localStorage.getItem('voice-plugin-gallery')||'[]').slice(0,24).map(validatePlugin)}catch{}
 function listPlugins(){$('pluginChoice').replaceChildren(new Option('插件关闭 / Plugin OFF',''),...curatedPlugins.map((p,i)=>new Option(p.name,'c'+i)),...gallery.map((p,i)=>new Option(p.name,'g'+i)));}listPlugins();
 async function usePlugin(p){try{if(!await plugins.load(p))return;const controls=plugins.current.params.map((p,i)=>{const label=document.createElement('label');label.textContent=p.name;const input=document.createElement('input');input.type='range';input.min=p.min;input.max=p.max;input.step=(p.max-p.min)/100;input.value=p.default;input.oninput=()=>plugins.set(i,Number(input.value));label.append(input);return label;});$('pluginParams').replaceChildren(...controls);}catch(e){$('pluginStatus').textContent=e.message;}}
 $('pluginChoice').onchange=()=>{const value=$('pluginChoice').value;if(!value){plugins.clear();$('pluginParams').replaceChildren();return;}usePlugin((value[0]==='c'?curatedPlugins:gallery)[Number(value.slice(1))]);};
 $('pluginSave').onclick=()=>{if(!plugins.current)return;gallery=[{...plugins.snapshot,seed:seed(),prompt:$('pluginPrompt').value},...gallery].slice(0,24);try{localStorage.setItem('voice-plugin-gallery',JSON.stringify(gallery));listPlugins();$('pluginChoice').value='g0';}catch(e){status(e.message)}};
 $('pluginExport').onclick=()=>{if(!plugins.current)return;const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify({...plugins.snapshot,seed:seed(),prompt:$('pluginPrompt').value},null,2)],{type:'application/json'}));a.href=url;a.download='visual-plugin.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 $('pluginImport').onchange=async()=>{try{const file=$('pluginImport').files[0];if(!file)return;if(file.size>100000)throw Error('Plugin limit: 100 KB');await usePlugin(validatePlugin(JSON.parse(await file.text())));}catch(e){$('pluginStatus').textContent=e.message}};
 $('pluginGenerate').onclick=()=>{if(zero())return;const started=performance.now();request('plugin',{prompt:$('pluginPrompt').value,style:$('style').value},d=>{if(d.plugin){usePlugin({...d.plugin,prompt:$('pluginPrompt').value,seed:seed()});modelLatency=Math.round(performance.now()-started);status('GPT-6 plugin: '+modelLatency+' ms');}if(d.error)status(d.error);if(d.status)$('pluginStatus').textContent=d.status});};
 $('connectome').onchange=()=>{connectome.canvas.hidden=!$('connectome').checked;$('connectomeStatus').textContent=connectome.available?'MaleCNS v1.0 · 317 neurons / 20,937 edges · 布局估计 / seeded force layout, not anatomy':'WebGL2 unavailable';};

 $('preload').onclick=async()=>{if(zero())return;setlist();for(const item of sections){if(zero())break;await request('section',{piece:item.name,style:$('style').value==='fusion'&&$('monetBlend').checked?'fusion+monet':$('style').value},d=>{if(d.brief)Object.assign(item,d.brief);if(d.error)status(d.error)});}brief=sections[Number($('section').value)]??brief;};
 $('generate').onclick=()=>{if(zero())return;const start=performance.now();request('scene',{transcript:$('text').value,scene:{...scene,style:$('style').value,monet:$('monetBlend').checked}},d=>{if(d.html){$('generated').srcdoc='<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; img-src data:">'+d.html;modelLatency=Math.round(performance.now()-start);status('GPT-6 · '+modelLatency+' ms');}if(d.error)status(d.error)});};
 $('zero').closest('label').hidden=true;for(const id of ['preload','generate','pluginGenerate','blenderStatus'])$(id).hidden=true;fetch('./api/status').then(r=>{if(!r.ok)throw Error();return r.json()}).then(()=>{$('zero').closest('label').hidden=false;for(const id of ['preload','generate','pluginGenerate','blenderStatus'])$(id).hidden=false;}).catch(()=>{});
 $('zero').onchange=()=>{controller?.abort();$('pluginGenerate').disabled=$('preload').disabled=$('generate').disabled=zero();if(zero()){$('generated').srcdoc='';document.querySelectorAll('video.blender').forEach(v=>{v.pause();v.classList.remove('visible')});setlist();}$('blenderStatus').textContent=zero()?'Zero-AI · tiers 2/3 OFF':'后台待命 / Backend standby';};
 $('savePiece').onclick=()=>{const p={libraryId,libraryIds:library.programIds,seed:seed(),settings,style:$('style').value,monet:$('monetBlend').checked,setlist:$('setlist').value,sound:$('soundMode').value,parts:$('pianoParts').value};try{localStorage.setItem('voice-performer-piece',JSON.stringify(p));status('作品已保存 / Piece saved')}catch(e){status(e.message)}};
 $('loadPiece').onclick=()=>{try{const p=JSON.parse(localStorage.getItem('voice-performer-piece'));if(!p)return;libraryId=p.libraryId??null;library.restore(p.libraryIds);for(const k of Object.keys(settings)){settings[k]=Math.max(0,Math.min(2,(Number.isFinite(Number(p.settings?.[k]))?Number(p.settings[k]):1)));document.querySelector('[data-mapping="'+k+'"]').value=settings[k];}$('seed').value=String(Number(p.seed)>>>0);$('seed').dispatchEvent(new Event('change'));$('style').value=p.style;$('monetBlend').checked=!!p.monet;$('setlist').value=p.setlist;$('soundMode').value=p.sound;$('soundMode').dispatchEvent(new Event('change'));$('pianoParts').value=p.parts;setlist();}catch(e){status(e.message)}};
 addEventListener('pagehide',()=>{recognition?.stop();stopSpeechAudio?.();midiStop?.();input.stop();controller?.abort()});setlist();
 function install(plan){onPlan?.(plan);directed=plan;directedIndex=0;directedStart=clock();brief={description:plan.description,family:plan.family,palette:plan.palette};libraryId='director';$('style').value=plan.style;scene.workStyle={family:plan.family,palette:plan.palette};}
 return {direct(plan){if(directed){directedNext=plan;return;}onInput();install(plan);},clearDirector(){directed=null;directedNext=null;queue=[];onMidi([176,64,0]);onMidi([176,123,0]);},connectMidi(){if(!midiStop)return $('midiInput').onclick(true);},painted(stats){if(pendingSpeech!==null){paintLatency=document.hidden?null:+(performance.now()-pendingSpeech).toFixed(2);pendingSpeech=null;}if(pendingMidi!==null){midiLatency=document.hidden?null:+(performance.now()-pendingMidi).toFixed(2);pendingMidi=null;}if(performance.now()-lastMetrics<200)return;lastMetrics=performance.now();$('benchMetrics').textContent=JSON.stringify({tier1_paint_ms:paintLatency,midi_to_render_ms:midiLatency,model_ms:modelLatency,plugin_draw_ms:+plugins.ms.toFixed(2),frame_ms:stats.frame_average_ms??null,visible:!document.hidden},null,2);},event,plugins,connectome,reset(){queue=[];music.reset();fileEvents=[];fileEnd=null;},get blender(){return blender.visible},frame(time,dt,base,a){input.update(time);if(directed){let seconds=60/directed.tempo;const duration=directed.beats*seconds;if(time-directedStart>=duration){queue=[];music.reset();onMidi([176,123,0]);if(directedNext){install(directedNext);directedNext=null;seconds=60/directed.tempo;}else{directedStart+=duration;directedIndex=0;}}while(directedIndex<directed.notes.length&&directed.notes[directedIndex][0]*seconds<=time-directedStart){const [beat,pitch,length,velocity]=directed.notes[directedIndex++];const start=directedStart+beat*seconds;enqueue([144,pitch,velocity],start);onMidi([144,pitch,velocity],'director',length*seconds);queue.push({time:start+length*seconds,data:[128,pitch,0],output:true});queue.sort((a,b)=>a.time-b.time);}}if(fileEnd!==null&&time>=fileEnd){fileEnd=null;library.finish();}while(fileIndex<fileEvents.length&&fileEvents[fileIndex].time<=time-fileStart){const e=fileEvents[fileIndex++];enqueue(e.data,fileStart+e.time);onMidi(e.data);}while(queue.length&&queue[0].time<=time){const e=queue.shift();music.midi(e.data,e.time);if(e.output)onMidi(e.data);}const f=music.update(time),mapped=pianoMapping(f,settings,seed(),brief);const active=!!directed||f.polyphony>0||time-f.lastInput<3;const evolution=active?{...base,...mapped.evolution,profile:{...base.profile,colours:mapped.evolution.profile.colours,...(libraryId?{family:brief.family}:{})},clock:time,deterministic:zero()}:base;const audio=active?{...a,level:Math.max(a.level,mapped.audio.level),pulse:Math.max(a.pulse,mapped.audio.pulse)}:a;plugins.draw(time,audio,evolution,seed());connectome.draw(time,dt,audio,evolution,$('style').value);if(time-lastUI>.2){lastUI=time;$('musicFeatures').textContent=JSON.stringify({key:f.key,chord:f.quality,tension:+f.tension.toFixed(2),notes:f.polyphony,pedal:f.pedal},null,2);}return {evolution,audio};}};
}
