// Cached, fixed worlds only. This module never calls a generation API.
export function chooseWorld(items,text){const words=text.toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').split(' ').filter(s=>s.length>2);const ranked=items.map(item=>({item,score:words.reduce((n,w)=>n+((item.piece+' '+item.movement+' '+item.brief).toLowerCase().replaceAll('-',' ').includes(w)?1:0),0)+(item.quality==='full'?.1:0)})).sort((a,b)=>b.score-a.score);return ranked[0]?.score>.1?ranked[0].item:undefined;}
export function worldCamera(time,f={},view=0){const dynamics=Math.max(0,Math.min(1,f.dynamics??0)),tension=Math.max(0,Math.min(1,f.tension??0)),arc=f.phraseArc??.5;const angle=time*.055+view,radius=.65;return {x:Math.sin(time*.023+view)*radius,y:Math.sin(time*.017)*.12,z:Math.sin(time*.019+view*.7)*radius+(arc-.5)*.3,yaw:angle+Math.sin(time*.027)*tension*.12,roll:Math.sin(time*.04)*tension*.015,exposure:.8+dynamics*.5,fog:.035+(f.pedalWash??f.pedal??0)*.1};}
export function worldLayer(stage,status){const base=location.hostname.endsWith('.github.io')?'https://voice-canvas.zhuoning2934293.workers.dev':'.';let engine,loading=false,entry=null,items=[],query='',failedQuery='',revision=0,view=0,wasCadence=false,lastCut=-Infinity,clock=0,lastTime=null,drag=null,yaw=0,pitch=0,dolly=0,quality=1,baseText='',movement='',tourView=0;const canvas=document.createElement('canvas'),fog=document.createElement('canvas');canvas.id='worldCanvas';fog.id='worldFog';canvas.hidden=fog.hidden=true;canvas.style.zIndex=1;fog.style.zIndex=2;stage.prepend(canvas,fog);const wash=fog.getContext('2d');
 async function init(){if(engine)return engine;const [THREE,{SparkRenderer,SplatMesh}]=await Promise.all([import('three'),import('https://sparkjs.dev/releases/spark/2.2.0/spark.module.js')]);const renderer=new THREE.WebGLRenderer({canvas,antialias:false,alpha:false,preserveDrawingBuffer:true});renderer.toneMapping=THREE.ACESFilmicToneMapping;const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(65,1,.03,150);scene.add(new SparkRenderer({renderer}));engine={THREE,SplatMesh,renderer,scene,camera,mesh:null};return engine;}
 async function select(text,marker=''){if(text===query&&(loading||entry||failedQuery===text))return;query=text;const version=++revision;loading=true;status('World 缓存载入中；实时画布继续');try{if(!items.length){const response=await fetch(base+'/worlds/index.json');if(!response.ok)throw Error('No cached worlds');items=(await response.json()).items??[];}const matching=marker?items.filter(item=>item.movement.replaceAll('-',' ').toLowerCase()===marker.toLowerCase()):[];const next=chooseWorld(matching.length?matching:items,text);if(!next)throw Error('No cached worlds');if(next.path===entry?.path){loading=false;return;}if(!/^[a-z0-9_/-]+\/$/.test(next.path)||!/^\w+\.spz$/.test(next.splat))throw Error('Invalid cached asset');const e=await init();const mesh=new e.SplatMesh({url:base+'/worlds/'+next.path+next.splat});await mesh.initialized;if(version!==revision){mesh.dispose();return;}const scale=Number(next.semantics?.metric_scale_factor)||1,offset=Number(next.semantics?.ground_plane_offset)||0;mesh.scale.setScalar(scale);mesh.rotation.x=Math.PI;mesh.position.y=offset;e.scene.add(mesh);if(e.mesh){e.scene.remove(e.mesh);e.mesh.dispose();}e.mesh=mesh;entry=next;view=0;tourView=0;clock=0;lastTime=null;status('World · '+next.piece+' / '+next.movement+' · '+next.quality+' · 自动环顾巡游 / Automatic camera tour');}catch(error){if(version===revision){failedQuery=text;entry=null;status('World 未缓存或载入失败；继续 Fusion / World unavailable; Fusion stays live');}}finally{if(version===revision)loading=false;}}
 stage.addEventListener('pointerdown',e=>{if(!canvas.hidden){drag=[e.clientX,e.clientY];stage.setPointerCapture(e.pointerId);}});stage.addEventListener('pointermove',e=>{if(!drag)return;yaw+=(e.clientX-drag[0])*.003;pitch=Math.max(-.65,Math.min(.65,pitch+(e.clientY-drag[1])*.003));drag=[e.clientX,e.clientY];});stage.addEventListener('pointerup',()=>drag=null);stage.addEventListener('wheel',e=>{if(canvas.hidden)return;e.preventDefault();dolly=Math.max(-1,Math.min(1,dolly+e.deltaY*.001));},{passive:false});
 return {canvas,fog,select,get ready(){return !!entry;},get current(){return entry;},get camera(){return engine?{position:engine.camera.position.toArray(),yaw:engine.camera.rotation.y}:null;},draw(time,dt,f={},enabled=false,text='',marker=''){
 if(text!==baseText){baseText=text;movement='';}if(marker)movement=marker;const wanted=text+(movement?' '+movement:'');if(enabled&&wanted!==query&&!loading)void select(wanted,movement);canvas.hidden=fog.hidden=!enabled||!entry;if(canvas.hidden){lastTime=null;return false;}
 const cadence=(f.cadence??0)>.4;if(cadence&&!wasCadence&&time-lastCut>8){view+=1.618;lastCut=time;}wasCadence=cadence;clock+=lastTime===null?0:dt*(.65+Math.max(0,Math.min(1,f.dynamics??0))*.7);tourView+=(view-tourView)*(1-Math.exp(-dt*.35));lastTime=time;
 const e=engine,b=stage.getBoundingClientRect(),ratio=Math.min(1.5,devicePixelRatio||1)*quality,w=Math.max(1,Math.round(b.width*ratio)),h=Math.max(1,Math.round(b.height*ratio));if(canvas.width!==w||canvas.height!==h){e.renderer.setSize(w,h,false);fog.width=w;fog.height=h;e.camera.aspect=w/h;e.camera.updateProjectionMatrix();}
 const p=worldCamera(clock,f,tourView);e.camera.position.set(p.x,p.y+(Number(entry.semantics?.ground_plane_offset)||0),p.z+dolly);e.camera.rotation.set(pitch,p.yaw+yaw,p.roll,'YXZ');e.renderer.toneMappingExposure=p.exposure;const start=performance.now();e.renderer.render(e.scene,e.camera);if(performance.now()-start>20||dt>.024)quality=Math.max(.45,quality*.97);wash.clearRect(0,0,w,h);const gradient=wash.createRadialGradient(w*.5,h*.5,0,w*.5,h*.5,w*.75);gradient.addColorStop(0,'rgba(222,226,235,0)');gradient.addColorStop(1,`rgba(222,226,235,${p.fog})`);wash.fillStyle=gradient;wash.fillRect(0,0,w,h);return true;
 }};
}
